### ISSUE TITLE
Some questions about the project

### ISSUE THREAD

**Issue by thugic** [andreapollastri/cipi#100]
Hey there!
This is a promising project, keep up with it!

Here's my two cents:

## Is there any specific reason you are not using Route-Model-Binding?
I'm referring to `server.servercode` and `applications.appcode`. Why not keeping the ID? This would make things a lot easier and code much cleaner.

## Sticking to conventions
In `RemoteController` responses should really be something more semantic and not just strings.

## Security
Shouldn't these routes be protected by `auth` middleware?
```
Route::group(['prefix' => 'remote'], function () {
    Route::get('/start/{servercode}','RemoteController@start');
    Route::get('/finalize/{servercode}','RemoteController@finalize');
    Route::get('/status/{servercode}','RemoteController@status');
    Route::get('/ping/{servercode}','RemoteController@ping');
});

Route::group(['prefix' => 'sh'], function () {
    Route::get('/go/{servercode}','ShellController@install');
    Route::get('/ha/{servercode}','ShellController@hostadd');
    Route::get('/hd/{servercode}','ShellController@hostdel');
    Route::get('/hg/{appcode}','ShellController@hostget');
    Route::get('/aa/{servercode}','ShellController@aliasadd');
    Route::get('/ad/{servercode}','ShellController@aliasdel');
    Route::get('/ag/{appcode}/{domain}','ShellController@aliasget');
    Route::get('/pw/{servercode}','ShellController@passwd');
    Route::get('/sc','ShellController@ssl');
    Route::get('/st','ShellController@status');
    Route::get('/dy','ShellController@deploy');
    Route::get('/nx','ShellController@nginx');
});
```

## Extracting to helpers?
You seem to be using `ssl_check` and `ssl` functions in  a lot of places. Consider to extract them as helpers??

## Move validation to FormRequests
Controller are really "fat". Validation and authorization should be moved to FormRequests.

## Server.complete ???
Server column has a field named `complete` but it is not clear why it is set as integer ...
4. `server.complete` is an integer that makes little to no sense ... (0, 1, 2??? what's 1 what's 0? 

## dbroot and passwords stored as plain text
I haven't investigated about this but is it safe to store server password and dbroot as plain text???

## `application` vs `applications`
These routes should really merge into one.

I'll PR something soon about some of these, but wanted to know if there were some specific reasons about your choices.

**Comment by thugic** [comment]
Ok, after some sourcediving I got some things a bit clearer.

 - about `servercode` and `appcode` we should move them to `uuid` and set those for route-model-binding. Would make things cleaner and more maintainable.

- about `auth` middleware on some routes: ok got it 😅(but this needs to be addressed nonetheless)

**Comment by andreapollastri** [comment]
Hi Zac,
thank you for the issue... so... I try to reply to your questions.

- About routes model bining: I wanted identify every server and application with an unique ID (not autoincremental) as Digital Ocean and AWS done with VPS because of:
    > future feautures (as data migrations)
    > leave unique and not autoincremental data between Cipi and remote child VPS (useful for remote scripting)

- Security in routes: if they are without auth middleware is because I need to expose that to child VPS (managed by Cipi) and I need to do it without any session or token! Any way there are NO SECRETS DATA exposed in that routes!

- Server.complete: you are right... this comes from v.1 ... now I had to rename it with "status"... I will do it in the next realeses.

- dbroot and passwords stored as plain text: yes, only in the Cipi main DB that can be secure and not expose in the web if we need but anyway I'm working on a different solution that isn't ready yet!

- Sticking to conventions / Extracting to helpers / Fat Controller / application vs applications: you are right... I'm developing in Laravel since 1 year, I never studied Computer science in my life... I was a sound engineer in the past.... I will fix it in next versions!

Bye
Andrea

**Comment by thugic** [comment]
> * About routes model bining: I wanted identify every server and application with an unique ID (not autoincremental) as Digital Ocean and AWS done with VPS because of:
>   > future feautures (as data migrations)
>   > leave unique and not autoincremental data between Cipi and remote child VPS (useful for remote scripting)

Ok, maybe this should be moved to UUID's and clean stuff a bit by making them th default route model key.

> * Security in routes: if they are without auth middleware is because I need to expose that to child VPS (managed by Cipi) and I need to do it without any session or token! Any way there are NO SECRETS DATA exposed in that routes!

As in my previous comment I got this ;)

> * Server.complete: you are right... this comes from v.1 ... now I had to rename it with "status"... I will do it in the next realeses.

Great!

> * dbroot and passwords stored as plain text: yes, only in the Cipi main DB that can be secure and not expose in the web if we need but anyway I'm working on a different solution that isn't ready yet!

;)

> * Sticking to conventions / Extracting to helpers / Fat Controller / application vs applications: you are right... I'm developing in Laravel since 1 year, I never studied Computer science in my life... I was a sound engineer in the past.... I will fix it in next versions!
> 

No worries. Since your target audience are developers, well, we need robust code to be running on our servers, so better be prepared! :)

I made a pull request BTW. 

Check it out.

**Comment by andreapollastri** [comment]
Great!
I accepted your PR (Thank You) and I just renamed "complete" in "status".
They will be included in the next release!

Thank You Zak!
