### ISSUE TITLE
Improve  cipi Login Security

### ISSUE THREAD

**Issue by rockethost-israel** [andreapollastri/cipi#107]
1. Two-factor Authentication
2. Verification code that will send by email or sms.
* after admin will first login to cipi and will enter his email/phone
it can work by creating simple onboarding on first login. at the "onboarding" admin can enter his email/phone for Verification code. also at the "onboarding" step we can ask admin more info and other "customizations" that he want.

**Comment by andreapollastri** [comment]
Hi... Thankyou for the issue... 2factorauth requires SMTP and other data that are not available by all. I would like to keep Cipi simple and easy-to-use but... Cipi basically is a Laravel project so if you need it you can add it using one of the several free Laravel 2factorAuth packages that you can find in Google. Sorry

Best
Andrea
