### ISSUE TITLE
add more server/site settings

### ISSUE THREAD

**Issue by rockethost-israel** [andreapollastri/cipi#108]
1. allow to set / change Time Zone (Server time)
2. install/remove php extensions for each php version
3. edit PHP settings like:
php_admin_value[display_errors] = "off"
php_admin_value[log_errors] = "On"
php_admin_value[mail.add_x_header] = "On"
php_admin_value[max_execution_time] = "120"
php_admin_value[max_input_vars] = "10000"
php_admin_value[memory_limit] = "512M"
php_admin_value[opcache.blacklist_filename] = "/opt/opcache-blacklists/opcache-*.blacklist"
php_admin_value[opcache.max_accelerated_files] = "100000"
php_admin_value[opcache.memory_consumption] = "256"
php_admin_value[output_buffering] = "4096"
php_admin_value[post_max_size] = "100M"
php_admin_value[short_open_tag] = "On"
php_admin_value[upload_max_filesize] = "100M"

4. add support for http2 and http3 and hsts
5. force Redirecting to https
6 show ssl status
7. allow to enable / disable gzip compression

**Comment by andreapollastri** [comment]
Thank You... this will be implemented... I move the issue in v3.

**Comment by gerryweb** [comment]
Is there a way to be able to carry out the suggestions already in the panel?
edit PHP settings like:
php_admin_value[display_errors] = "off"
php_admin_value[log_errors] = "On"
php_admin_value[mail.add_x_header] = "On"
php_admin_value[max_execution_time] = "120"
php_admin_value[max_input_vars] = "10000"
php_admin_value[memory_limit] = "512M"
php_admin_value[opcache.blacklist_filename] = "/opt/opcache-blacklists/opcache-*.blacklist"
php_admin_value[opcache.max_accelerated_files] = "100000"
php_admin_value[opcache.memory_consumption] = "256"
php_admin_value[output_buffering] = "4096"
php_admin_value[post_max_size] = "100M"
php_admin_value[short_open_tag] = "On"
php_admin_value[upload_max_filesize] = "100M"

**Comment by LemarinelNet** [comment]
> 5\. force Redirecting to https

That features seems really important today.
Google gives bad scores to websites not having HTTPS, but even more, as a visitor, when hitting on "www.mysite.com" and seeing "this website is not secured" is frightening... 
Being redirect is a MUST !
