### ISSUE TITLE
Redis integration

### ISSUE THREAD

**Issue by andreapollastri** [andreapollastri/cipi#109]

**Comment by JFOC** [comment]
hi,
is this redis meaning adding support to have Redis cache configuration for a site and server ?

**Comment by andreapollastri** [comment]
Hi JFOC! 
Yes.. Redis is Ready to be configured with you WP o Laravel or any other PHP app for sessions or caching.

The configuration is:
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379
