### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by shad0wfir3** [andreapollastri/cipi#118]
Hey, @andreapollastri I have just installed cipi on a digital ocean droplet, wanting to use test it out to see if it can become our future deployment software. Curious though, the setup does not set up a default interface and site. I have checked the sites-enabled folder and it seems that default Nginx config is in place, but binds to an empty folder

Secondly, during the installation process, I get an "Error: retrieving gpg key timed out". This can be bypassed by ctr+c however a few python scripts backtrace.

The process finish, but then as mentioned there are no accessible URLs, or Nginx sites installed. 

Could you please shed some light on this?

**Comment by andreapollastri** [comment]
Hello @shad0wfir3, I just tryed to install Cipi on different Digital Ocean VPS and everything works fine! As you can see: 
- MAIN SERVER: http://157.245.177.42/
- CHILD SERVER: http://167.99.173.128/
Did you use Digital Ocean installation via password or key? I used password mode.
If you want we can have a Skype or Google Hangsout call with screen share useful to show the right way to install Cipi! Let me know!

**Comment by andreapollastri** [comment]
@shad0wfir3 .. I'll switch off VPSs soon... let me know if do you want / need a call via Skype togheter... in the meanwhile I just pubblished the first version of Cipi Documentation: https://cipi.sh/docs/.

I hope to hear from you soon.
Best

Andrea

**Comment by shad0wfir3** [comment]
Hey, @andreapollastri thank you for the reply, so I noticed the issue was with the Ubuntu 20 version. I dumped the machine, spun up a new v18 LTS one and it installed perfectly. I am playing around with it, loving the idea, and would like to start contributing. Especially considering that i would need connections to be made available to for integrations into 3rd party providers and also git connection and deploys. 

Is these requirements in line with your development roadmap?

**Comment by shad0wfir3** [comment]
Docs looking good as well, very well done on this project. I can see that there is git functionality. Would be good to work that into the web interface.

**Comment by andreapollastri** [comment]
Hi @shad0wfir3! I'm glad to hear it from you!
About 3rd parts provider integration it's a good idea! I'll work on it!
About Git connect I quickly developed a sort of Github deploy script... you can find more info into the Docs: https://cipi.sh/docs/.
(maybe I will integrate Git, backups, crons and Supervisor into Cipi Web Panel) in next releases.
Anyway.. If you want collaborate in this or other idea/feature you are welcome! :)

If you have any issue write here or via mail because every feedback is useful to improve Cipi Core!!!

Best
Andrea

**Comment by shad0wfir3** [comment]
I would definitely love to help out and contribute, I just have a few projects to get out of the way, and then ill start contributing where i can. I look forward to seeing more of cipi! Again, well done, and keep up the good work.

**Comment by andreapollastri** [comment]
Perfect @shad0wfir3! Thank You for the compliments about Cipi! I close this ticket! Best. Andrea
