### ISSUE TITLE
SSL Certificate and Cloudflare

### ISSUE THREAD

**Issue by Xoshbin** [andreapollastri/cipi#119]
Hi, In the documentation you mentioned "and that there is not any proxy in the middle (such as Cloudflare proxy for e.g.)." what if there is proxy especially Cloudflare. how it can be solved please. if there's a solution it's better to mention it in the documentation. I'm checking this package with every update because I really like it and I want to transfer to CIPI. but my concern is I want to check that it has all the requirements that I need then implement it for production.
Another thing which I think I should open another issue for it but anyway I will put it here is, it's better to have a log file for deploy.sh script because sometimes when you push to GitHub and the deploy.sh script runs you may have errors but if there's no log file you may not see it.
Thanks for the great package

**Comment by andreapollastri** [comment]
HI @Xoshbin. Thank You for your response!
About SSL, no worry to use CloudFlare (or any other WAF/CDN service)... Let's Encrypt work on DNS validation so if you need to obtain a certificate via Let's Encrypt on your domain you have to disable for a moment Cloudflare proxy on that DNS but after Let's Encrypt Validation you can reactive it! Or you can alse use directly Cloudflare Certificate. I updated the Docs. I hope that now is clear... let me know if I have to improve it! 
About log in deploy.sh you are right... I'm working to move deploy, cron, backup and supervisor scripts into Cipi Panel web interface with a simple UI and usage of them without SSH in next releases and deploy log will be included. You have to wait some weeks for it but with "Cipi migration" function you could update your Cipi in future without losing anything about your setup and data. :)

**Comment by Xoshbin** [comment]
Thank you @andreapollastri for the hard work and for the great package. I will test it out and I expect for sure to see more features in this great package. Thank you again.

**Comment by andreapollastri** [comment]
You are welcome @Xoshbin! I hope that you enjoy Cipi! Any problem/issue write me!

**Comment by Xoshbin** [comment]
Sorry @andreapollastri you mentioned that I can update CIPI with "Cipi migration" how is that please?

**Comment by andreapollastri** [comment]
Hi @Xoshbin!
It's simple... for e.g.:
- you install current Cipi Version (2.4.7) on a VPS and you use it to deploy 8 child VPSs.
- in the future you would install a new Cipi Version (e.g. v3.2) but you have to mantein your 8 VPS control and bring them on your new panel so...
- if you go in "settings" area... you can export all VPSs data into a "secret" key that you will import on the new Cipi Panel with a click and you grant the control of you 8 child VPSs also into the new panel! so you can than switch off the old 2.4.7 version and work only with new 3.2

Sorry for my bad english... I hope that is understandable! :)

**Comment by Xoshbin** [comment]
Great, Thank you again. And don't worry my English is not better than yours :)
