### ISSUE TITLE
Support for SlickStack (and other FOSS stacks?)

### ISSUE THREAD

**Issue by jessuppi** [andreapollastri/cipi#120]
Hey Andrea, I've seen Cipi mentioned a few times recently and very cool, mate. I've been surprised how long it has taken for a FOSS version of the _million-and-one_ deploy panels to emerge... esp. since some of the commercial ones have poor LEMP configuration (or bundle Apache).

I'm wondering if you've considered supporting existing WordPress stacks like SlickStack (which I'm currently maintaining on GitHub) and other non-Docker LEMP stacks.

For example: SlickStack, Webinoly, WordOps, etc... CentminMod is CentOS-based.

https://github.com/littlebizzy/slickstack

Public config mirrors: http://mirrors.slickstack.io

I don't have any plans to integrate a control panel or UI, in the hope that SlickStack could potentially integrate with existing or future deployment tools. (I do believe WordOps is building their own UI so I'm not sure if that would potentially conflict or overlap with Cipi.)

It might also allow you to focus more on the control panel, and vice-versa.. or at least provide for more integration/options between FOSS projects.

Anyway just a thought, and I figured I'd mention this publicly. Cheers and great work!

**Comment by andreapollastri** [comment]
Hi @jessuppi!  Thank You for your response! ;) I'm glad to hear that from you!
I don't know SlickStack but I'll evalute it soon and I will update you!

Best
Andrea
