### ISSUE TITLE
2 servers minimum?

### ISSUE THREAD

**Issue by NanoG6** [andreapollastri/cipi#121]
Hi, so I need two servers minimum to get this panel full functioning? One for control panel, and one for the web server, correct?
Somewhere in the documents, I read that the control panel can't be installed on NAT VPS, my current setup is I have many cheap low-spec NAT VPS that I want to utilize as a control panel, can I use that NAT VPS behind nginx reverse proxy?
Thank you

**Comment by andreapollastri** [comment]
Hi @NanoG6 ... Right, the simplest way to install Cipi is via autoinstallation script but it requires 2 servers... anyway Cipi is just a simple Laravel project so if you have a Lamp/Lemp hosting useful to install it, you can install Cipi via composer (without autoinstall shell script) and use it to deploy other VPS without using a dedicated server for Cipi. If you need help to do it contact me.

About NAT VPS, I'm sorry but currently I can't give you a real and definitive response... Cipi is well tested on:
- Digital Ocean
- AWS ec2
- Vultr
- Google Cloud
...many users currently use Cipi on several other providers but in the past, I had some response from some of them about some issue with NAT VPS... it would be amazing if you'll check it on your configuration... I can give you support also via Skype / Slack or Teams if you want.

**Comment by andreapollastri** [comment]
Hi @NanoG6 ... can I close the issue? Do you need help with Cipi?

**Comment by andreapollastri** [comment]
HI @NanoG6. I confirm that NAT VPS are not supported by Cipi. I close this issue. If you need help open another issue or write me on Cipi Slack channel / hello@cipi.sh. Best
