### ISSUE TITLE
Wildcard, Email Server, and Wordpress

### ISSUE THREAD

**Issue by JFOC** [andreapollastri/cipi#125]
Hi,
Does it support:
1. Wildcard Letsencrypt
2. Letsencrypt proxy for a domain name is not using CF nameserver
3. Wordpress Multisite auto-setup
4. Email server + management

**Comment by andreapollastri** [comment]
Hi @JFOC! Currently I'm working on V.3 that will includes Wildcards for SSLs and Cloudflare integration. It will be ready in the first part of 2021.
WP autoinstallation script and other one-click apps installations will be ready on next September.
E-mail Server is not in roadmap but I will decide if include it in the future.
