### ISSUE TITLE
Add mongoDb

### ISSUE THREAD

**Issue by smkoBa** [andreapollastri/cipi#126]
HI  @andreapollastri its a good idea to add MongoDb. It's very good for nosql dB.
use [laravel-mongodb](https://github.com/jenssegers/laravel-mongodb) for laravel support
Thanks for good your project.

**Comment by andreapollastri** [comment]
Hello @smkoBa ! Thank You for your feedback!
I will evaluate Mongo DB support in next Cipi version (v3).
