### ISSUE TITLE
No uninstall script

### ISSUE THREAD

**Issue by cybermonkj** [andreapollastri/cipi#129]
Cipi killed my litespeed server

**Comment by andreapollastri** [comment]
Hi @cybermonkj.
As I wrote in documentation, Cipi is for "fresh Installation" of Ubuntu 18.04 or 20.04 LTS!
So you need to install it only on clean VPS (not preinstalled and preconfigured).
I'm sorry about your issue but Cipi is not compatible with a Litespeed configured system.
As wrote in Cipi website and docs, it requires fresh Ubuntu installation.

**Comment by andreapollastri** [comment]
PS @cybermonkj if you need help to uninstall every single Cipi Components I can help you if you need

**Comment by zharn** [comment]
Is there any way to remove the whole setup of cipi.sh?
Or deleting php8 , ngnix seperately will remove?
