### ISSUE TITLE
Can't see Application other than PHP

### ISSUE THREAD

**Issue by bilalinamdar** [andreapollastri/cipi#137]
Dear Team,

This was my first time deploying CIPI and i found no Application (only PHP).
I am confused on exactly why the applications are missing such as wordpress,magento.
Am i doing something wrong ? I tried to deploy on my personal cloud.
![image](https://user-images.githubusercontent.com/7912006/90334129-ed029e80-dfe8-11ea-80ba-9287cd1ba097.png)

Also while installing "server" ubuntu 20.04 i got this issue 
![image](https://user-images.githubusercontent.com/7912006/90334152-128fa800-dfe9-11ea-8a4c-4b301ef17c99.png)

Very nice project. I am looking forward for the answer.

**Comment by andreapollastri** [comment]
Hi! Sorry for the late reply! 
I'll check for Ubuntu 20 installation, Thank You for the issue!
About Application what's the issue? You can installa your own PHP applications based on a specific PHP version as you need. In version 3 (not now) you could choose a pre-installed script such as Laravel, Wordpress, ...
