### ISSUE TITLE
Nginx reverse proxy apache

### ISSUE THREAD

**Issue by safalshrestha** [andreapollastri/cipi#138]
Hi, I have been using moss.sh for a while now but its shutting down in couple of months. I discovered this after searching for a replacement. I rely on .htaccess file alot and prefer nginx as a reverse proxy to apache setup. I was just wondering of there is a way to setup this cipi.

I am guessing if I install Apache manually and configure nginx, it might work but would it be possible to support this setup by any chance? Looking forward to use this and thanks for the great work.

**Comment by HeatherFeuer** [comment]
I have the same question/issue. I am currently running multiple servers on Moss and need to find a new panel. I need to have .htaccess capability with WordPress so I would need nginx as a reverse proxy to apache. Is it possible to have this configuration?

**Comment by andreapollastri** [comment]
Hello! Currently Cipi doesn't support Apache Reverse Proxy but you can configure in easy way nginx into Cipi to make the same directive of .htaccess... if you need help contact me.

I'm working on v.3 and maybe Apache/nginx proxy will be included because of the request as yours are many!

**Comment by safalshrestha** [comment]
@andreapollastri I am trying to do this by adding a proxy pass for PHP. It works but its a hassle to go through all the projects. I tried the project and liked it. Yeah a native nginx reverse proxy apache would be great in my opinion. Not only in terms of performance but would help people migrating from cpanel and continue to have .htaccess directives.

Thanks again for the great work.

**Comment by andreapollastri** [comment]
Hi @safalshrestha sorry for the late reply. 
I'll deploy it in v.3. Thank you for the support
