### ISSUE TITLE
Not able to view my application page

### ISSUE THREAD

**Issue by tax-pages** [andreapollastri/cipi#143]
i used cipi to deploy my application on AWS lightsail, but after deployment i am keep on getting the cipi server up page not my application page. following is my ip address http://52.221.214.16/, i deployed laravel app, and twice checked my nginx.conf for root folder.

**Comment by tax-pages** [comment]
i tried re deploying using cipi on a new lightsail instance having ip 13.212.97.103, just to check i hav'nt missed anything, but no success, i have installed application checked using terminal that my application exists and in its root folder i also have index.php, but still on hitting my ip i still get "Server Up!" not the what written in index.php
can someone guide what i am missing?

**Comment by andreapollastri** [comment]
Hi! Currently Cipi has some issue with AWS litesail ... use EC2... I'm really sorry... in v3 I'll fix it!

**Comment by tax-pages** [comment]
thanks for the reply, can ec2 support laravel with vue? i was trying to deploy my laravel-vue application with ec2 but its only deploying php not the npm.
