### ISSUE TITLE
DNS issues

### ISSUE THREAD

**Issue by ninety3** [andreapollastri/cipi#144]
how to add subdomain on your server? i have a laravel application that makes unlimited domains like company1.domain.com, company2.domain.com etc, how can i manage this without creating Aliases?

**Comment by andreapollastri** [comment]
Hi.. .sorry for late reply.
all you have to do is create one or more applications in Cipi (that are such as virtualhostes) then you have to associate to every applications one or more domains.... if you use more than one domain/subdomain you have to use application aliases. 
Let me know if it's clear! Best
Andrea
