### ISSUE TITLE
Uninstall Cipi from vps vultr

### ISSUE THREAD

**Issue by lore77** [andreapollastri/cipi#145]
Hello Andrea, by mistake I installed cipi in a vultr vps with another cpanel administrator, and now I cannot access the sites error service unavailable, can you tell me how the tool can be uninstalled? thanks

**Comment by andreapollastri** [comment]
Hi, there is not any uninstall script... you have to manually unistall everything. 
If you need support about what Cipi installs on server write me but Cipi has to installed on a clean Linux installation... not on a cPanel server. sorry

Best
Andrea
