### ISSUE TITLE
Read / Write issue filezilla and other deployment tools

### ISSUE THREAD

**Issue by tax-pages** [andreapollastri/cipi#147]
i am unable to upload a single file using filezilla, whenever i try to upload a single php file it said permission denied i had to upload zip using filezilla and then have to connect to the server and use root credentials to unzip that, if i use application user credentials then i canont even unzip the file...

**Comment by ninety3** [comment]
i solved this issues by changing user and group from root to that specific user. 
i find something suspecious, when i create an app, user is created at that time, web and public folder permission is assigned to that user but all other folders that are in web has "root" as their owner, so to connect to that application either i have to change my web folder group or all other folders user and group.
please have a look at this.

**Comment by andreapollastri** [comment]
Hi, sorry for the late reply... my last month was terrible. I'll fix it on v3 that will be relese in the first part of 2021 in the meanwhile the solution of @ninety3  works!
