### ISSUE TITLE
Installation interrupted on ubuntu server 20.04

### ISSUE THREAD

**Issue by jimisens** [andreapollastri/cipi#148]
I'm trying to install a server running in AWS
Y already try 3 times, reinstalling a new fresh install each time. 
But in the server the installation is interrupted with the following error. 

E: The repository 'http://ppa.launchpad.net/certbot/certbot/ubuntu focal Release' does not have a Release file. 
N: Updating from such a repository can't be done securely, and is therefore disabled by default. 
N: See apt-secure(8) manpage for repository creation and user configuration details.

With this the server appear like "IS COMMING" in my dashboard. I suppose because the installation is not finish. 

What can i do please ?

**Comment by andreapollastri** [comment]
Hi, sorry for the late... I know it, I'm working to solve it... in v3 that will be released soon, this bug will be fix! Sorry!
