### ISSUE TITLE
Few questions?

### ISSUE THREAD

**Issue by magix01** [andreapollastri/cipi#150]
Hi guys,

I have notices this is new project, serverpilot and runcloud wont be happy about this, thats for sure 👍 

1. How secure is the login page or do i need to add some firewall rules?
2. Are users of each apps jailed?
3. Does destination (added) server communicate with panel server over some port like serverpilot or dest server pings panel from the inside?
4. What ports are open by default?
5. How secure are destination servers, how do the auto package update?
6. Can we use apache .htaccess for wordpress sites its needed?

Edit: I have also found an issue, when viewing access logs the IP of request is show as IP of cloudflare when using cloudflare instead of that of visitor, eg. 162.158.94.199 <- this is CF proxy IP.

Thank you for this project i am just testing it.

**Comment by magix01** [comment]
Is this abandoned, i see last commit 4+ months ago?

**Comment by andreapollastri** [comment]
Hi! The project is still alive and currently I'm working on version 3 that will be ready on first part of 2021. 
Sorry if I'm not full time on Github but I've a full time job and in this period I can't follow issues here but the version 3 will be ready soon and will solve many issues that I read everyday anyway!

About your questions:

1 - How secure is the login page or do i need to add some firewall rules?
The login page is based on Laravel Authentication so if you use a complex password the security is OK!

2 - Are users of each apps jailed? Yes!

3 - Does destination (added) server communicate with panel server over some port like serverpilot or dest server pings panel from the inside? No, it's a secure SSH connection on standard 22 port communication

4 - What ports are open by default? Only 22/80/443 as documented

5 - How secure are destination servers, how do the auto package update? Security updates are enabled by default and they run automatically

6 - Can we use apache .htaccess for wordpress sites its needed? No, Cipi is only nginx based... the configuration for WP is ready yet by default but if you need to custom it follow the docs: https://cipi.sh/docs/ (Customize nginx section).

Best,
Andrea

**Comment by magix01** [comment]
Thank you for your time, this will be interesting.

Regards

**Comment by magix01** [comment]
Just a suggestion i have been thinking, since the exchange happens with ssh/22 could it be possible then to make panel connect to cloud servers instead of other way around, that we we could use panel on localhost or behind firewalls not exposing it to public. Is this possible?

**Comment by kernelhacks** [comment]
Can CIPI be used to resell the VPS/Droplets from digitalocean or any other VPS provider?

**Comment by andreapollastri** [comment]
@magix01  I'm working to improve that part in v3.

@kernelhacks Sure! Currently you can install Cipi into DO droplets... in the future you will be able to run new droplets directly through Cipi.

**Comment by ovizii** [comment]
> Just a suggestion i have been thinking, since the exchange happens with ssh/22 could it be possible then to make panel connect to cloud servers instead of other way around, that we we could use panel on localhost or behind firewalls not exposing it to public. Is this possible?

That sounds great, it looks wasteful to run a whole server just for cipi so having it run locally would be great.
