### ISSUE TITLE
Centos 8

### ISSUE THREAD

**Issue by giorgosstab** [andreapollastri/cipi#152]
its possible to run this script at centos?

**Comment by andreapollastri** [comment]
Hi, No Sorry, as other similar Control Panels, Cipi runs and will run only on Ubuntu.

**Comment by giorgosstab** [comment]
i dont think so..i know many control panels run in multiple os..btw better os for control panel and security is centos. thanks for answer btw.. happy coding

**Comment by andreapollastri** [comment]
Uhmmm... You are right if you mean cPanel, Plesk, ... but Cipi similar products such as Server Pilot, Ploi, Runcloud, ... runs all on Ubuntu. I'm sorry but the effort required to make a CentOs Cipi version is not in my plans. I'm really sorry.
