### ISSUE TITLE
Any Possibility of Apache ??

### ISSUE THREAD

**Issue by qzoke** [andreapollastri/cipi#154]
Hi, Is there any chance of Apache + Nginx as Reverse Proxy instead of Nginx as Main Server Handling Request.

 I  have read it on multiple blogs. Here is one of them : 
 
 https://www.cloudways.com/blog/wordpress-nginx-with-apache/

The reason I am locking for Apache is because of htaccess file, modules and its familiarity. But Also speed of Nginx.

**Comment by andreapollastri** [comment]
Hi, I know that .htaccess is very useful but I'm sorry, I'll not include Apache in v3.
