### ISSUE TITLE
Installation failure $'\r': command not found

### ISSUE THREAD

**Issue by vincentbitter** [andreapollastri/cipi#155]
When I try to install via 
`wget -O - https://cipi.sh/go.sh | bash`
on Ubuntu 18 (64 bit) the following exception is thrown
`$'\r': command not found`

This probably means the file is saved in a Windows format.

It works fine if I try to install via
`wget -O - https://raw.githubusercontent.com/andreapollastri/cipi/master/setup/go.sh | bash`

**Comment by andreapollastri** [comment]
Hello! Thank You for the issue, recently I changed hosting VPS for cipi.sh website breaking go.sh file. Now it's fixed! Thank You
