### ISSUE TITLE
Removing Self Manager feature

### ISSUE THREAD

**Issue by kassemz** [andreapollastri/cipi#156]
I see on the road map for V3 https://github.com/andreapollastri/cipi/projects the Self Manager feature.

I think Cipi should stay away from this feature (ability to host apps on the control node) so the control node is focused on what it needs to do, control other servers. For example if one of the apps hosted on the control node is consuming a lot of resources, this would affect the reliability of the control node which should be working and monitoring other servers at all times. What do you think?

**Comment by andreapollastri** [comment]
HI! This is a good point of view, let me think about it because currently I'm developing v.3 yet. I'll notice to you my decision soon. Thank You for the issue!

**Comment by magix01** [comment]
@andreapollastri 

Well you could always leave option to install it as C&C center or locally as other webpanel. I am testing your panel for few months, the stack is really stable and fast. You should just better support cloudflare, logs dont show real user ip but cloudflares for instance, wordpress wp-admin goes into infinite redirect loop when on cf etc... But overall keep the good work :)

**Comment by andreapollastri** [comment]
Thank You for your feedback @magix01  ... I'm working to improve Cipi in version 3. I hope that it will be a great product!

**Comment by ovizii** [comment]
I'm happy I found this thread as I was wondering (after reading the cipi official docs page) whether cipi has to be installed on a separate Server or on one of the managed servers.

**Comment by ovizii** [comment]
I also think that the description is a bit misleading "An Open Source Cloud Control Panel" 

maybe that should be changed to "A self-hosted Open Source Cloud Control Panel" to make it clearer? 

Or maybe you want to offer it as a hosted service?

**Comment by kassemz** [comment]
Thanks @andreapollastri 

I noticed there are no commits related to V3 on master branch and no related branches, a different repo?

**Comment by andreapollastri** [comment]
@kassemz yes... I'm working on it in a private repo for my personal reasons... I'll pubblish it in next days... when I'll be ready

**Comment by andreapollastri** [comment]
Self managment currently is in V3 but is such as "optional"... you can use Cipi to control only other servers without any problem
