### ISSUE TITLE
Wilcard domain

### ISSUE THREAD

**Issue by magix01** [andreapollastri/cipi#158]
Hi,

is it possible to create wildcard domain so all domains that are not defined, but pointed to server can use the same public_html folder?

@andreapollastri 
Regards

**Comment by andreapollastri** [comment]
Hi @magix01 .. shure! You can set a domain alias as *.domain.ext but you cannot generate a Let's Encrypt Wildcard in current version of Cipi ;/ so if you need SSL you have to declare every single subdomain or use an external service such as Cloudflare or https://punchsalad.com/ssl-certificate-generator/ 

In Version 3 I'm working to enable SSL wildcards!

**Comment by andreapollastri** [comment]
Nope... in current v3, SSL Wildcards are not supported... maybe in the future, I'm Sorry :(
