### ISSUE TITLE
No cURL in php?

### ISSUE THREAD

**Issue by magix01** [andreapollastri/cipi#163]
I have noticed there is no curl extension in php, tested with php 7.4, dont know about other versions.

I installed it with root: 

sudo apt-get install php7.4-curl

Then restarted nginx service, however i think you should include this by default since lots of licencing plugins for wordpress use curl.

Regards

**Comment by kassemz** [comment]
Yes definitely, PHP curl is essential.

**Comment by andreapollastri** [comment]
Hi! Thank You for the issue... I'll investigate and solve it in v3! Thank You and sorry for my bad .... I checked it... now I'll recheck it!

**Comment by andreapollastri** [comment]
Solved in current V3
