### ISSUE TITLE
How about a dockerized version?

### ISSUE THREAD

**Issue by ovizii** [andreapollastri/cipi#164]
A while ago, I started running most of my "smaller" projects and apps inside docker containers behind a reverse proxy (traefik in my case) - seeing the low system requirements of cipi this should be doable too.

What are the dev's thoughts on this?
Doable, not doable, makes no sense, etc.?

**Comment by andreapollastri** [comment]
Hi, Thank You for the issue. I confirm that v3 is fully localhostable and that it will use Docker to run! So you a have to wait 2 weeks for next version ;)

**Comment by hesyar** [comment]
Does this mean that it also would run within kubernetes?

**Comment by andreapollastri** [comment]
Partially solved in Cipi v3... you can dockerize it but you have to expose your local project to a public IP during the operations on the servers.

**Comment by ovizii** [comment]
> Partially solved in Cipi v3... you can dockerize it but you have to expose your local project to a public IP during the operations on the servers.

Would you mind giving me some more pointers on how to do this? I am sure its not as easy as creating a docker container based on ubuntu 20.4 and add:
RUN wget -O - https://cipi.sh/go.sh | bash 

I would give it a go if I had some ideas where to start especially since you said its partially solved.
