### ISSUE TITLE
GD Library missing

### ISSUE THREAD

**Issue by magix01** [andreapollastri/cipi#165]
Hi, tested on php 7.4, GD library is missing please add that to the ver 3 release, as wordpress auto thumbnail generator depends on it. I have installed it with:

sudo apt-get php7.4-gd

Then restarted nginx, however gd should be there by default.

regards

**Comment by andreapollastri** [comment]
Hi! Thankyou for the issue... I'll investigate and solve it in v3! Thank You

**Comment by andreapollastri** [comment]
Solved in current V3
