### ISSUE TITLE
No server after install

### ISSUE THREAD

**Issue by LucioSaldivar** [andreapollastri/cipi#166]
After a sucessful install of Cipi. I log in and find that there are no servers registred. When I try my servers IP to add it, it says that I cannot set up Client server or Cipi server. 

New to all of this and am currently running my own home server. Ubuntu 20.04

**Comment by andreapollastri** [comment]
So... it will not show you your server IP?

**Comment by LucioSaldivar** [comment]
Correct. I bought a server and would like to use this panel for it. 

I freshly installed Ubuntu 20.04 on the server, connected it to my router, and successfully installed Cipi.

Now I don't know what the next steps are since I can't do much without creating a server but now sure how to go about that since I only have one.  Does this only work for Virtual Machines?
![Capture](https://user-images.githubusercontent.com/43145025/108796294-04998180-754e-11eb-9e6d-72cceefde32a.PNG)
![Capture2](https://user-images.githubusercontent.com/43145025/108796296-05321800-754e-11eb-82be-2b89f1bd98fd.PNG)
![Capture3](https://user-images.githubusercontent.com/43145025/108796298-05caae80-754e-11eb-9ee0-b1f4fcd0a22f.PNG)

**Comment by kingingspree** [comment]
If I understand you correctly, you installed this on your server, we'll call it server A. Then you are trying to connect said server, server A, with it as well? I do not believe that is possible. Usually with these platforms, the servers have to be in a clean slate. Someone correct me if I am wrong? Thanks

**Comment by ovizii** [comment]
as far as I understand, cipi does not get installed on the server you want to manage, apparently that is on the roadmap. So basically you need a server to install cipi and then one or more you want to be managed by cipi.

**Comment by andreapollastri** [comment]
Hi currently (v2), Cipi is such as ploi.io, runcloud, serverpilot and similar SaaS but in v3 it will include self manage feature!

**Comment by joglomedia** [comment]
> Hi currently (v2), Cipi is such as ploi.io, runcloud, serverpilot and similar SaaS but in v3 it will include self manage feature!

can't wait for the v3 :heart_eyes:

**Comment by andreapollastri** [comment]
Solved in current version 3 (now in beta... soon in LTS)
