### ISSUE TITLE
Slack notifications?

### ISSUE THREAD

**Issue by magix01** [andreapollastri/cipi#167]
Could it be possible to implement slack notifications with email ones, should not be too hard, just a field for webhook and the messages could be email body ones?

**Comment by andreapollastri** [comment]
Hi @magix01 in stable version 3 Slack notifications will be include

**Comment by andreapollastri** [comment]
Nope... in current version external integration are not supported... I'm Sorry ;( but... you can use Cipi API to integrate Cipi Core into your own business logic.
