### ISSUE TITLE
Cipi doesnt show after install

### ISSUE THREAD

**Issue by Raheemshah2809** [andreapollastri/cipi#169]
Hi all, so basically i ran the command and it said it was installed successfully, 
it gave me a link and ip address so i can acess cipi, ive entered the link in the browser andit doesnt show me the dashboard for some reason. this is waht is shows me. 

<img width="961" alt="Screenshot 2021-03-14 at 18 39 52" src="https://user-images.githubusercontent.com/66431658/111080081-ac262600-84f4-11eb-94f1-479d2b60f94e.png">

**Comment by andreapollastri** [comment]
Hi! In your image I can see Apache ;( are you sure that you installed Cipi on a clean Ubuntu VPS?!? I think that you installed it on a preinstalled VPS. I'm sorry!
