### ISSUE TITLE
Access to the panel.

### ISSUE THREAD

**Issue by osidney** [andreapollastri/cipi#176]
I just performed an installation of Cipi, at the end he informed credentials of root SSH and root MySQL accesses, however with root SSH credentials I was unable to log in to the panel, is there a standard user or does it need to be created manually?

**Comment by andreapollastri** [comment]
You are right! I forgot to write it... First access to panel is: administrator / 12345678!
Then you can update your credentials into Settings Area ... Tomorrow I will update the Readme.
Thank you for the issue

**Comment by osidney** [comment]
@andreapollastri Thanks.
