### ISSUE TITLE
Unable to install *stuck*

### ISSUE THREAD

**Issue by magix01** [andreapollastri/cipi#178]
DigitalOcean 20.04 LTS, console:

<code>
root@CIPIV3TEST:~# wget -O - https://cipi.sh/go.sh | bash
--2021-03-18 11:03:11--  https://cipi.sh/go.sh
Resolving cipi.sh (cipi.sh)... 104.16.244.78, 104.16.243.78, 2606:4700::6810:f34e, ...
Connecting to cipi.sh (cipi.sh)|104.16.244.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16913 (17K) [text/x-sh]
Saving to: ‘STDOUT’

-                   100%[===================>]  16.52K  --.-KB/s    in 0.001s

2021-03-18 11:03:11 (27.2 MB/s) - written to stdout [16913/16913]

</code>

Also tried on 18.04 same thing happens.

**Comment by magix01** [comment]
Hmm, after chmod +x on go.sh local download and then running it with ./go.sh the installation appears to start normally.

**Comment by andreapollastri** [comment]
OK! Thank You for the issue... I'm happy that you have solved your issue but I'll investigate on this case (never happened in my tests). Let me know (site edit section is incomplete but your Cipi will be auto - update when I'll release new features).

**Comment by magix01** [comment]
@andreapollastri 

I like the new look, just checked a few features, panel seems nice.. will wait for stable and lts before i migrate :)

**Comment by duydinh71** [comment]
Hi Andrea Pollastri,
I have same install issue on my fresh ubuntu droplet DigitalOcean. 
I found out that /dev/random not running so I changed it to /dev/urandom and it's working.
PASS=$(head -c 16  /dev/urandom | md5sum | cut -f 1 -d\ )
DBPASS=$(head -c 16  /dev/urandom | md5sum | cut -f 1 -d\ )
SERVERID=$(head -c 16  /dev/urandom | md5sum | cut -f 1 -d\ )
I hope you investigate on this case. 
Thank you for developing a great software.
Sincerely,
Duy Dinh

**Comment by andreapollastri** [comment]
Fixed auto installation script bug in Digital Ocean... thank you for the issue! ;)
