### ISSUE TITLE
Initial Server preinstalled

### ISSUE THREAD

**Issue by zarulizham** [andreapollastri/cipi#18]
Hello. Is it possible to have server preinstalled in the Cipi Manager?

Currently my step is:
1. Create new EC2 Instance in AWS
2. `wget -O - https://cipi.sh/go.sh | bash`
3. Login into Manager
4. Add new Server
5. Copy and paste script shown into EC2 (created at step 1) 

But somehow the Manager is reset after Step 5 is completed.

**Comment by andreapollastri** [comment]
Hi! Cipi needs a standalone VPS or laravel hosting to manage one or more external VPSs.
Are you installing Servers into the same EC2 VPS? Let me know.

Bye
Andrea

**Comment by zarulizham** [comment]
Yes, for now I'd like to manage server and install Cipi in a same EC2 VPS. I am grateful is there any ways to make it happen

**Comment by andreapollastri** [comment]
I’m Sorry! What you require is not Cipi concept.
Cipi lets you to manage several VPSs so you have to use a standalone istance. 

Maybe in the future I’ll release a Cipi “light” version that manages a single self server but not soon.

Cipi is different than cPanel, Plesk and others.

**Comment by zarulizham** [comment]
Oh sorry for the misunderstanding. Thank you for the explanation and carry on the good work :)
