### ISSUE TITLE
Connect to DigitalOcean, Vultr, Hetzner, etc... using api keys for easy deployment

### ISSUE THREAD

**Issue by aobweb** [andreapollastri/cipi#187]
It would be awesome if we could Connect to DigitalOcean, Vultr, Hetzner, etc... using api keys for easy deployment. Ploi.io uses this method to make it super easy to deploy servers on any cloud platform. I think it would be a great enhancement, and I'm ready to make a donation for this project for such feature to be implemented.

**Comment by andreapollastri** [comment]
Hi, you are right. Cipi Version 3 has an auto update system and I'm working on several improvements that will be integrated in next months. So I think that this feature will be available this summer. Thank You for the issue.
