### ISSUE TITLE
mistake

### ISSUE THREAD

**Issue by dimonpanik** [andreapollastri/cipi#189]
https://github.com/andreapollastri/cipi/blob/4f83a08b88f5448dab786f6dc128834b81d247dd/resources/views/settings.blade.php#L265

**Comment by techieshark** [comment]
@dimonpanik are you able to elaborate? I'm just another user and I do not see what you are trying to say

**Comment by dimonpanik** [comment]
@techieshark well, an error in the word password. Sorry for the empty request, it just hurts my eyes

**Comment by railto** [comment]
Was actually quicker to fork the repo, fix the issue and submit the PR than it would have taken to open the ticket, just saying.

**Comment by andreapollastri** [comment]
HI! Thank You for the issue and sorry for the late... this is a busy week but I'll fix and release other stuff on Cipi 3 in next 2 days.

**Comment by andreapollastri** [comment]
Thank You for the PR @railto, it has been merged into 3.x branch and it will be released in next hours in Cipi version 3.0.1.
