### ISSUE TITLE
My cipi did not update automatically. What to do?

### ISSUE THREAD

**Issue by wesleydeveloper** [andreapollastri/cipi#199]

**Comment by andreapollastri** [comment]
Is it remains a version 3.0 and not to 3.0.1?

**Comment by wesleydeveloper** [comment]
is still in version 2.4.9. Ubuntu 18.04

**Comment by andreapollastri** [comment]
Ah OK! I'm sorry but auto update function is available only since version 3.0. I know that is a bullshit reinstall everything but since v3 the updates works without issues.

**Comment by wesleydeveloper** [comment]
how do i migrate without losing connection to the running instances?

**Comment by wesleydeveloper** [comment]
OK! I will do this. Thanks!

**Comment by andreapollastri** [comment]
You cannot migrate from v2 to v3, sorry! 
Since v3.0 any future version will be compatible but there is a breakchange from 2 to 3 so you have to reinstall sites. Sorry
