### ISSUE TITLE
How to setup SSL for the main instance?

### ISSUE THREAD

**Issue by zietbukuel** [andreapollastri/cipi#20]
Should I go ahead and install certbot myself and install the SSL? Or is there a more elegant way to do this? I'm talking about the server where CIPI is installed. 
Maybe the installer should do this by default?
Thanks.

**Comment by andreapollastri** [comment]
Hi! Currently you can add quickly, safetly and in a esy way a SSL certificate to all "client" servers but not to main Cipi server so, I'll take care about your needed and I'll deploy a new version with that feature but for the moment you have to do it manually, sorry!
