### ISSUE TITLE
Redirect a sites www.* goes to /login page

### ISSUE THREAD

**Issue by ialexpw** [andreapollastri/cipi#218]
Hi there,

Just installed Cipi and liking it so far.

I've added a site to it (e.g. domain.com) and added an Alias of www.domain.com and then enabled SSL. That works and when I visit domain.com it shows the "Coming soon" page, but if I visit www.domain.com it seems to redirect to www.domain.com/login which is showing the Cipi login page.

Is this something I've configured incorrectly or is there a way around this?

Thanks and great work!

**Comment by andreapollastri** [comment]
Hi! Thankyou for the issue! 
I'll check the Alias script today and I'll update this issue. 

Best

Andrea

**Comment by andreapollastri** [comment]
There is a bug... I'm fixing it! The patch will be ready soon in version 3.0.6. Thank You for the issue

**Comment by andreapollastri** [comment]
Hi @ialexpw,
I just commit a fix that will solved aliases and related SSL certs issues.
This patch will be available in Cipi v3.0.6... your Cipi Panel will be automatically update this night. 
Thank You again for the help with this bug ticket. Let me know if with new version you will have any issue again.

Best
Andrea
