### ISSUE TITLE
Support for OpenVZ

### ISSUE THREAD

**Issue by zietbukuel** [andreapollastri/cipi#22]
When using the OpenVZ platform I get the following error when building a new slave node. This doesn't happen on other providers that use KVM for example.

```
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 1.83906 s, 584 MB/s
mkswap: /var/swap.1: insecure permissions 0644, 0600 suggested.
Setting up swapspace version 1, size = 1024 MiB (1073737728 bytes)
no label, UUID=080d1090-4e93-4193-88a2-4dbf56cff97c
swapon: /var/swap.1: insecure permissions 0644, 0600 suggested.
swapon: /var/swap.1: swapon failed: Operation not permitted
```

The installer script should detect OpenVZ (or at least respect if it already has swap enabled) and skip this step as this breaks the installation process.

http://people.redhat.com/~rjones/virt-what/

**Comment by andreapollastri** [comment]
I'm fixing it in the new version. Sorry but for the moment I've not got any solution.
