### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by eninja-gh** [andreapollastri/cipi#226]
Hello There,

I'm getting 502 Bad Gateway after installation ... how can I fix it?

**Comment by andreapollastri** [comment]
Hi! What provider are you using? In some of them such as Contabo many users have issues and I have to investigate why... I think that it doesn't use standard repositories for PHP!

**Comment by eninja-gh** [comment]
Unfortunately, I'm using Contabo ... How can I send you root login details for you to check or, which repository do you want me to add before running CPI installation?

**Comment by andreapollastri** [comment]
I'm working on a patch for Contabo! Currently I have not solutions for it! In any other provider that I tried, Cipi works... but I will release a patch soon! I'm really sorry to don't be able to solve the situation in this moment. I suggest to you to try to install manually PHP FPM 7.3,7.4 and 8.0 and relative extensions.

Remember that Cipi disable root access after installation and you have to use auto generated Cipi user that is a root user. 

Let me know... I will update this issue when the Contabo patch will be ready!

**Comment by andreapollastri** [comment]
I close the issue and I will notify to you when the patch is ready!

**Comment by Teclehome** [comment]
Hello, I'm in the same situation on the contabo server. You can also let me know when you resolve this issue. I look forward to testing CIPI.

**Comment by andreapollastri** [comment]
Contabo VPS bug will is fixed. You have to install from zero on a clean Ubuntu 20.04 VPS, CIPI version 3.0.9 that will be released in the next hours!  I'm really sorry about this issue that is restricted to Contabo VPSs only.

**Comment by hxinen** [comment]
No wonder... I had to reinstall 3x

**Comment by andreapollastri** [comment]
The problem was related to PHP official packages that on Contabo didn't work :(
Now I solved it but you have to reinstall Cipi from zero on your Contabo VPS (clean installation of Ubuntu 20.04).
Version 3.0.9 has been released now and it works! I'm sorry... I'm not a Contabo user and in any other VPS Cipi worked fine... now it works also in Contabo, thankyou for the issue and sorry for the reinstallation. I hope you enjoy Cipi!

**Comment by hxinen** [comment]
I don't think it works. I reinstalled my OS and Cipi
![image](https://user-images.githubusercontent.com/7673032/116403622-603efe80-a860-11eb-8d54-73a6249656f4.png)

**Comment by andreapollastri** [comment]
Really sorry!

**Comment by andreapollastri** [comment]
Ok! I released version 3.0.9 with an error, really sorry... Version 3.0.10 works... this is a brand new Contabo S size VPS within Cipi 3.0.10: http://167.86.90.245/ 

Now it works without issues. Thank You for the ticket.

**Comment by andrewgosselin** [comment]
Hey I just installed the latest version of Cipi on a new install of Ubuntu 20.0.4 on a Contabo L size VPS and I am getting a 502 Bad Gateway. When installing it I noticed it couldn't find a bunch of PHP 8 packages so I assume it's the same missing repository issue listed above.
