### ISSUE TITLE
How to SSH into slave nodes as root?

### ISSUE THREAD

**Issue by zietbukuel** [andreapollastri/cipi#23]
I lost root access to a node after installing it as a slave node. How can I recover root access? Or at least access to a privileged user so I can perform admin tasks such as software updates?

**Comment by andreapollastri** [comment]
Hi! Sorry for the late reply!
You can connect to your VPS with a no root user than elevate your login to root with:
su -root command.

let me know!
Best
Andrea

**Comment by zietbukuel** [comment]
Do I have to create this user previously or do I get one as part of the installation process? Because when I setup a server I only have a root user, so when I install the software I lose access to the server.

**Comment by andreapollastri** [comment]
Hi,
right! when you start to install you start with a root user that your VPS provider gave to you but, for security reasons Cipi disables it and change SSH port from 22 to 1759 so if you want to access with root privilege you have to connect into your server with a simple (not roor) user and elevate your access to root (with the same old password of the starter root user).
Cipi doesn't change your original root password.
Let me know!

**Comment by LewisSmallwood** [comment]
@zietbukuel I've just proposed a change which will allow passwordless SSH to any servers managed by the Control Panel from the control panel root account. By setting `ENABLE_SSH_ROOT_ACCESS=1` in the `/cili/.env` file before adding your server.

This will enable you to:
`ssh root@Your-Server-IP` without using a password whilst you are logged into your Control Panel server.

e.g.

SSH into Control Panel -> Then SSH into any managed server without a password.
