### ISSUE TITLE
No panel access after the Installation 

### ISSUE THREAD

**Issue by LuisBeOnline** [andreapollastri/cipi#24]
hello,

I'm not able to find the panel after the instalation. When I go to the ip I only get the apache page :|

**Comment by andreapollastri** [comment]
Hi Luis,
Con you give more details of your installation? VPS provider, OS, procedure, errors in installation bash run... let me know!

**Comment by LuisBeOnline** [comment]
I'm using a t2.micro from AWS with Ubuntu 18 server
The instalation seems to run until the end with no errors, and only stops with access url and admin credentials.

**Comment by andreapollastri** [comment]
Hi! I tried with AWS t2.micro and I didn't have any issue... it's difficult to investigate your problem without any screenshot or detailed error.
Sorry
