### ISSUE TITLE
Manager Backup

### ISSUE THREAD

**Issue by LemarinelNet** [andreapollastri/cipi#240]
Hi

Not related to site's backup, but this time to Manager backup : 

What would happen if one's cipi "manager" server crash : how would you put it back starting from scratch, and getting your sites back ? That would be almost an impossible task !

Cipi should include a manager backup (essentially a db backup ?)

Spatie/laravel-backup is something I use on my laravel projects, it could be a good candidate to start something about manager backup ?

**Comment by andreapollastri** [comment]
Hi, about Backup, currently Cipi has not any Backup tool so you have to provide them with VPS snippets or with a dedicated package such as Spatie backup. In next releases I'll introduce backup options to S3 systems.
