### ISSUE TITLE
Using blade

### ISSUE THREAD

**Issue by tyronehey** [andreapollastri/cipi#242]
I have a suggestion. We can use the blade for script generation. It allows us to generate dynamic scripts, for example, having a select box when creating a new server to install PostgreSQL/MongoDB instead of MySQL if users want it or using blade's condition for allowing users to don't install Redis/Node if they don't want to and lot more.

 I want to contribute, so If you need help, let me know.

**Comment by andreapollastri** [comment]
Hi, Thank You for the issue but Cipi uses Blade yet and doesn't support Postgre, mongo and node.
