### ISSUE TITLE
Unable to delete site after creation and cannot SSH to sites

### ISSUE THREAD

**Issue by MichaelWinson** [andreapollastri/cipi#243]
After I created a test site on a fresh installation of Cipi, unable to delete back from the dashboard as well as using API call. Can anyone guide me if there is a specific way to delete the site or any steps that I am not aware of? I am hosting on AWS EC2 instance. I only managed to delete the sites after I open the security group inbound rule to all traffice allow, which is of course not a good practice. Unable to figure out how to access to sites' folder through ssh, it does not recognised the password.

**Comment by andreapollastri** [comment]
Hi, can you give me more detail about this issue? I can't recreate your case for investigate the issue. Hear from you soon. Thank You
