### ISSUE TITLE
When i change PHP-FPM version i get 502 Bad Gateway

### ISSUE THREAD

**Issue by ketihar** [andreapollastri/cipi#245]
I use cipi on Digital Ocean VPS. Everything worked ok accept PHP-FPM version change. I used php 8.0 on a domain but when i try to change version to 7.4 or 7.3 i was getting 502 Bad Gateway. when returned to php version 8.0 the problem is solved. Restart PHP-FPM did not work.

**Comment by andreapollastri** [comment]
Hi, will check this case and I'll update this issue. Thank You for report this incident.

**Comment by karnaukhm** [comment]
same thing for me 3.0.10.
Looks like nginx config still tries to reach php 8 socket instead of selected php version

**Comment by andreapollastri** [comment]
Hi... a new version has been released within a fix for this and other issues! Sorry for the late
