### ISSUE TITLE
System error

### ISSUE THREAD

**Issue by ribafs** [andreapollastri/cipi#248]
First thank you for your good software.

I install the latest version (3.0.10) and when access web panel, after login, display error message
"ops! something went wrong... try later!"
And dont synchronize RAM, CPU and HDD.
Help me, please.

**Comment by andreapollastri** [comment]
Hi! Can you give me more details? I can't help you! If you want write me some more detail at mail@andrea.dev.

**Comment by ribafs** [comment]
Thank you. I send a email for you.

**Comment by WalysonGO** [comment]
Estou passando pelo mesmo erro! 
Alguém poderia me ajudar? 
**Lang[pt-br]**

**Comment by ribafs** [comment]
Im now using CyberPanel

**Comment by andreapollastri** [comment]
Hi... a new version has been released within a fix for this and other issues! Sorry for the late
