### ISSUE TITLE
Security issue when SSH connection fails

### ISSUE THREAD

**Issue by LewisSmallwood** [andreapollastri/cipi#25]
When the connection fails to a server, when the host is online but the SSH client is inaccessible, the Session's Server/Request Data is dumped in an error log.

This is a potential security issue as the error message includes the root database passwords, and additional data such as `USER_EMAIL`, `USER_PASSWORD` and any other environment variables like AWS tokens `AWS_SECRET_ACCESS_KEY`.

Steps to reproduce:
1. Change the port number for SSH (on a server that hosts applications) from `1759` to `22` in `/etc/sshd_config`
2. From the controller, create a new application.

Proposed fix:
Environment variable to turn off error reporting in production?

**Comment by andreapollastri** [comment]
Hi Lewis,
you are right! I didn't manage SSH key remote access.
By default my Digital Ocean gives me user and password so I don't use SSH key but I'll integrate an exception into .env file. 

Thank You for your advice... currently I have not so much to integrate new features into Cipi but I promise that I will make it in the next weeks... if you want to try to do it on this open source project you are welcome.

I will notice to you the progress of this task when I will start it!

**Comment by LewisSmallwood** [comment]
Hi Andrea,

I will try to add support into Cipi for SSH Key authentication to allow DigitalOcean users to make use of the feature. This will mean that SSH could still be hosted on port 22 rather than obscuring it. 

The feature would prevent the need for storing passwords in the database in plain-text (in a future release).

On systems that use SSH key based authentication, they have password authentication disabled by default so this will help make any Servers using Cipi more secure against brute-force attacks.

Shall I fork and branch from develop, then do a pull request afterwards?

Lewis

**Comment by LewisSmallwood** [comment]
I've implemented SSH Key-Based authentication between the Control Panel and servers in PR #26
