### ISSUE TITLE
Issue with local setup on Xubuntu 20.04

### ISSUE THREAD

**Issue by magix01** [andreapollastri/cipi#250]
Hi i tried to install on local network xubuntu 20.04 cipi panel and installation is complete, panel works but when i try to create local website this happens and spins all the time:

![image](https://user-images.githubusercontent.com/19437230/119997032-94c4e800-bfcf-11eb-9494-43affd075652.png)

I have public ip with ports forwarded 80 and 22, know why this happens?

regards

**Comment by andreapollastri** [comment]
Xubuntu is not officially supported, sorry! use Ubuntu 20.04.
