### ISSUE TITLE
Development environment

### ISSUE THREAD

**Issue by rubensrocha** [andreapollastri/cipi#251]
I would like to test some things and try to contribute to the project. How do I create a local development environment (Laradock / Docker / Devilbox)?

Os: Linux Mint
Dev: Laradock

**Comment by andreapollastri** [comment]
Hi... you can use Sail or similar Docker project. Cipi is a standard Laravel Project BUT ... it's  impossible to simulate locally the server management logic... so you can run it locally but you have to manage REAL VPSs.
