### ISSUE TITLE
Deploy via Github? Advice and guidance please,

### ISSUE THREAD

**Issue by SpaceIgniter** [andreapollastri/cipi#254]
Hi :)

I've managed to install Cipi, but I'm not winning by Deploying to my Server via Github.
The Cipi documentation isn't helpful in this regard either.

Could anyone please give me advice and guidance how to deploy Wordpress?
I guess if I see the proper steps to deploy Wordpress, I will be able to do it with other Github branches in future.

Thank you,
Enjoy the rest of the weekend.

**Comment by andreapollastri** [comment]
Hello! 
About Github deploy you can find more info at: https://cipi.sh/docs.html link. 
The steps are: 
> Set Github repository and branch into a Site
> Add deploy key into github.com (https://github.com/settings/ssh/new)
> Run deploy script via SSH (git/deploy.sh)

About WP, I'm working on Application auto-install function but if you want to install it, currently you can do it:
- in "classic way" via SFTP
- via Composer (composer create-project johnpbloch/wordpress .)

Let me know if it's OK
Andrea
