### ISSUE TITLE
how install ionCube?

### ISSUE THREAD

**Issue by hkbbdx** [andreapollastri/cipi#255]
Site error: the ionCube PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.

php7.4

**Comment by hkbbdx** [comment]
Does it seem to support online file management and PHP extension installation?

**Comment by joglomedia** [comment]
> Does it seem to support online file management and PHP extension installation?

You could install PHP extension via ssh console to the VPS/instance

**Comment by andreapollastri** [comment]
Hi... ionCube is not supported by Cipi in Official way so you can do it manually (e.g. https://www.tecmint.com/install-ioncube-loader-in-ubuntu-debian/) but I cannot offer to you support in this case. Best. Andrea
