### ISSUE TITLE
Mysql : "Out of sort memory" error

### ISSUE THREAD

**Issue by LemarinelNet** [andreapollastri/cipi#258]
I'm trying to make a SELECT on a table with about 3000 records, with an order by clause. 
Laravel is thrown an error by Mysql : 

  SQLSTATE[HY001]: Memory allocation error: 1038 Out of sort memory, consider increasing server sort buffer size 

Never seen such error on any of my other hosting services :)

My server has "881Mb" free memory (as seen in "free" command)... So surely not a server memory-full related error... 

Perhaps a mysql configuration ?

**Comment by andreapollastri** [comment]
Hi! Sorry for the late... I never seen it... I try to do some test trying to recreate the error. In the meanwhile try to restart mysql service and retry the query. Sorry for the issue... I'll solve it in next version!

**Comment by LemarinelNet** [comment]
Thanks for having a look. I've already tried to restart the service, with no effect.

Do you want a database dump to try to reproduce ?

**Comment by andreapollastri** [comment]
Hi, really sorry for the late reply... 
try to SSH into your VPS as "cipi" and run:

```
sudo nano /etc/mysql/mysql.conf.d/mysqld.cnf
sort_buffer_size = 256000000
sudo service mysql restart
```

Let me knwo
