### ISSUE TITLE
Does SSL installation work?

### ISSUE THREAD

**Issue by osidney** [andreapollastri/cipi#259]
I set up the master installation and a second server, set up CloudFlare on time and when I try to generate SSL on the panel's domain or on some website it doesn't work.

**Comment by andreapollastri** [comment]
Hi... You have to open 443 into your servers generating an SSL cert from Cipi ... just 1 for server than you can re-proxy your domain via Cloudflare... let me know if it works!

**Comment by osidney** [comment]
Strange is that all servers I work port 443 by default is open!

**Comment by andreapollastri** [comment]
Hi... a new version has been released within a fix for this and other issues! Sorry for the late
