### ISSUE TITLE
I cannot enter the CIPI panel

### ISSUE THREAD

**Issue by gerryweb** [andreapollastri/cipi#260]
Installation in an oracle cloud VPS with ubuntu Canonical-Ubuntu-20.04-2021.05.13-0
1ocpu, 1gb ram 46gb storage
Finish the installation and give me:
SSH root user, SSH root pass,  MySQL root user, MySQL root pass
But when entering the url it appears
Can't access this website

**Comment by andreapollastri** [comment]
Hi... I'm really sorry about it... did you receive some error during installation?

**Comment by gerryweb** [comment]
No, I am going to perform a new installation and I check if it marks an error and I publish it.
If oracle cloud is compatible with CIPI?

**Comment by andreapollastri** [comment]
I really don't know... I tested Cipi on:
- AWS
- Digital Ocean
- Linode
- Vultr
- Azure
- UpCloud
- Alibaba
- OVH
- Aruba
- Contabo
- Hetzner 
- Webdock
- Krystal 
and many other providers... but I never tried Oracle. Maybe is not compatible... it depends if Oracle use some custom repository for the server provisoning or some custom version of OSs.

**Comment by gerryweb** [comment]
This is the version that is installed from OS
Canonical-Ubuntu-20.04-2021.06.03-0

**Comment by andreapollastri** [comment]
yes but sometimes some provider uses custom repositories for OS, extensions and other installations... try to lookup for some error during installation process and let me know!

**Comment by gerryweb** [comment]
Only mistake
![error1](https://user-images.githubusercontent.com/70297971/124186149-814ee600-da81-11eb-820e-34156986fab3.jpg)

I already have the accesses and I have the same error
![error2](https://user-images.githubusercontent.com/70297971/124186406-e30f5000-da81-11eb-9f4b-2c01a6d04e1f.jpg)

**Comment by gerryweb** [comment]
In the Oracle instances you have to enable the permissions also in the firewall and with that it is solved
