### ISSUE TITLE
Login to panel as site user but not administrator?

### ISSUE THREAD

**Issue by John-S4** [andreapollastri/cipi#261]
When you create a new site then a new SSH / SFTP user and a new database user is created, which is great and as it should be.

It would also make sense and be really useful though if a new user was created also in the panel, so that someone can log in and administer one site without having access to all sites and the panel admin settings. 

Does it do this already and I am missing it somewhere or is this something that doesn't exist at the moment?

A further step would be if the administrator could create users in the panel and assign certain sites or servers to them, but that is a much bigger task and a whole other level of user management. 

A new panel user being created for each site seems like something that is logical and pretty essential if you are hosting multiple sites and servers though.

**Comment by andreapollastri** [comment]
Hi, Thank You for the issue! I'll notice this "nice to have" for next releases.
