### ISSUE TITLE
SSH login by key

### ISSUE THREAD

**Issue by John-S4** [andreapollastri/cipi#262]
Since Cipi removes the default root user on the server and creates a new one, it would be a big plus to have the option to log in as the new 'root' user by SSH key instead of password. 

By default I set all servers to use only keys for root login, but Cipi deletes that possibility and reverts me back to using a password.

**Comment by andreapollastri** [comment]
Hi, SSH key are not (and will be not) supported by Cipi. Sorry.

**Comment by LemarinelNet** [comment]
> Hi, SSH key are not (and will be not) supported by Cipi. Sorry.

SSH keys are way more secure than password.
I manually set them on every site I setup, and I agree that would be a big plus

**Comment by andreapollastri** [comment]
Hi! You are right but this feature will not be implemented in Cipi, sorry!

**Comment by LemarinelNet** [comment]
May I help if I provide a PR ?

**Comment by andreapollastri** [comment]
Hi @LemarinelNet ... Thank You for the idea, I think that Cipi has to be "simple" for major users. I agree with you about security issue of password but SSH Keys is not so easy for base user. 
So I think that is better to leave password mode and I suggest to you to use your VPS provider Firewall to limit the 22 port to your trusted IPs. 

In the meanwhile I plan an optional mode for SSH Key in version 4. Thank You for the issue!

**Comment by LemarinelNet** [comment]
Using a ssh key doesn't mean you have to remove/forbid password login.
You can still login using a password even having an SSH key set.
I don't even think it will make the app "more complex" or less simple. Users who doesn't want to use SSH key will still have a password set, and those who want to set a ssh key (I use them for [deployer](https://deployer.org/), my favorite deploy solution...) will just have to paste their ssh key in the given input box...
