### ISSUE TITLE
How do I edit the PHP configuration on a specific site?

### ISSUE THREAD

**Issue by gerryweb** [andreapollastri/cipi#263]
edit PHP settings like:
php_admin_value[display_errors] = "off"
php_admin_value[log_errors] = "On"
php_admin_value[mail.add_x_header] = "On"
php_admin_value[max_execution_time] = "120"
php_admin_value[max_input_vars] = "10000"
php_admin_value[memory_limit] = "512M"
php_admin_value[opcache.blacklist_filename] = "/opt/opcache-blacklists/opcache-*.blacklist"
php_admin_value[opcache.max_accelerated_files] = "100000"
php_admin_value[opcache.memory_consumption] = "256"
php_admin_value[output_buffering] = "4096"
php_admin_value[post_max_size] = "100M"
php_admin_value[short_open_tag] = "On"
php_admin_value[upload_max_filesize] = "100M"

**Comment by andreapollastri** [comment]
Hi this feature will be available in next release (September 2021)

**Comment by andreapollastri** [comment]
It will be included in version 4 (may 2022... sorry for the late)
