### ISSUE TITLE
backup site vps

### ISSUE THREAD

**Issue by netwebvn** [andreapollastri/cipi#264]
Hi! i found this to be a very good control panel, hope to have more features like automatic backup of all my websites and the option to save the number of backup files, like the last 3 to 5 files! Thanks the author!

**Comment by magix01** [comment]
There is rest api available, you can make those featured.

@andreapollastri 
No new commits for 3 months? Do you plan any update to cipi?

Regards

**Comment by andreapollastri** [comment]
Hi! Backup feature is under construction. I will update repo in September 2021 with new features and bug fix. 

The project is alive and I'am working on an optimized 3 version.

**Comment by netwebvn** [comment]
> There is rest api available, you can make those featured.
> 
> @andreapollastri
> No new commits for 3 months? Do you plan any update to cipi?
> 
> Regards

i really like laravel and having full rest api will be really helpful for developers to make the console more widely available!

**Comment by netwebvn** [comment]
> Hi! Backup feature is under construction. I will update repo in September 2021 with new features and bug fix.
> 
> The project is alive and I'am working on an optimized 3 version.

Thank the author very much! Looking forward to your new update will add this feature!

**Comment by andreapollastri** [comment]
Hi, sorry for the late reply! The panel is still alive but I was very busy with my business work. Now I can return to work on Cipi in my free time! I'll fix all issues in a next 3 version and I'm working on a Laravel 9 porting for the next release... sorry for the late... I hope to solve everything soon and that you will love new Cipi version!

**Comment by andreapollastri** [comment]
It will be included definitely in next version (may 2022)
