### ISSUE TITLE
Alias on Wrong Site

### ISSUE THREAD

**Issue by bhhenry** [andreapollastri/cipi#266]
Clean install of cipi 3.0.10 on Ubuntu 20.04 on Digital Ocean.

I set up one site as example1.com and add alias www.example1.com -- works fine.

I set up a second site as example2.com and then add alias www.example2.com to it. Problem is that www.example2.com is added to example1.com site instead of example2 site where it should be.

Thanks for your efforts :-)

**Comment by magix01** [comment]
Yeah i can confirm, same thing happening to me, added about 10 sites, and for each site i create alias it adds to the one "second site".

**Comment by HomaEEE** [comment]
Hello, who can have fix for this? or where to look?

**Comment by andreapollastri** [comment]
Hi... Sorry for the late reply... I'll check it soon... Thank You for the issue!

**Comment by andreapollastri** [comment]
It has been solved on today release! It will autoupdate your server this night... let me know if it's OK!
