### ISSUE TITLE
Make node.js optional

### ISSUE THREAD

**Issue by magix01** [andreapollastri/cipi#268]
Hi,

could you make installing node.js optional on servers with an installation prompt, since this is mostly php panel alot of users i guess never use node.js, i for instance remove it on each cipi install.

Thanks

**Comment by andreapollastri** [comment]
Hi... thank you for the issue and sorry for the late reply! No! Node is useful for NPM and modern SPA based frontend ... it comes within Cipi stack! Sorry!
