### ISSUE TITLE
Changing the main domain of the site caused an error

### ISSUE THREAD

**Issue by dij0990** [andreapollastri/cipi#269]
Hello.
Thank you for such a great app!

I ran into a problem, when I tried to change the main domain on the slave server, the domain changed on another one. This is strange, but as it is.

I created a new subdomain in digitalocean and tried to install it, however, it does not change it...

I temporarily changed the settings in nginx, however, they will most likely be reset at the next update.

how can I fix this now?

Is it possible to do this through the CIPI database?

Panel version: 3.0.10

**Comment by andreapollastri** [comment]
Hi... thank you for the issue and sorry for the late reply! you have to change it in DB and nginx configs... I'll check this issue!

**Comment by andreapollastri** [comment]
Hi... I solved this issue... your Cipi will be auto update its self this night! Sorry for the issue!
