### ISSUE TITLE
Style and theme repositories

### ISSUE THREAD

**Issue by LewisSmallwood** [andreapollastri/cipi#27]
Themes could include the abilities to:

- Add a logo and/or sidebar colours to the control panel.
- Change the default website for the child servers to host their own template site when accessed by IP directly.

**Comment by andreapollastri** [comment]
Hi, Thank You for SSH pull... You are great! 
I'll release your pull in the next version... now is in current master branch. 
I can make these your requests in the next days and include them in the next version.

if you want make some other pull to the project feel free to do it. 
I'm happy to have collaborators and if this project grows.

Talk to you soon (I will notify you my next steps).

**Comment by LewisSmallwood** [comment]
Thanks, Andrea!

I will have a look at adding themes and will open a pull request soon.

I'm thinking of making a change that adds an environment variable that points to a GitHub repo with theme files in. Something like `THEME_REPO_URL`.

That way the HTML from the install scripts can be separated and set externally.

By doing a `git pull` during the install process to pull in theme repositories, people could fork a base version and create their own themes by modifying their repo URL in the environment variables.

Would be open to other suggestions too.

Lewis

**Comment by andreapollastri** [comment]
Hi Lewis, It was fixed...sorry for the late support... my last months were very hard! This is a good Idea! I'm working on the version 2 that will be release in the last part of december... if you want I can include your idea if you create it! ;)

**Comment by andreapollastri** [comment]
I will close this issue because I think that Cipi is an Open Source tool for Developers first not for ISP so if any ISP wants to use Cipi, it can customize the template into code by itsself. I don't want to create a facility into my product to let people make money customizing logo and template and reselling services.
