### ISSUE TITLE
New Install - Stuck at 'wait'

### ISSUE THREAD

**Issue by josephasmith1** [andreapollastri/cipi#270]
Installed on Ubuntu 20.04 fresh updated install. I can access the panel, but 404 errors to fa-icons and the server screen just stays on "wait". I can't add sites. Under ip is just says cipiip and the details printed at the end of install do not contain an ip address(not sure if this is related).

![image](https://user-images.githubusercontent.com/6611890/134825688-5e51b548-7bf5-4ea3-8d0f-d17b39bcb50c.png)

**Comment by andreapollastri** [comment]
Uhm... thank you for the issue and sorry for the late reply... I'll check it soon!!! It seems like your Supervisord jobs don't work!

**Comment by andreapollastri** [comment]
I checked the system and it works! I can't replicate the error... are you sure are you working on a real public IP?

**Comment by Donniewr** [comment]
> I checked the system and it works! I can't replicate the error... are you sure are you working on a real public IP?

I'm getting the same issue, unable to use Cipi on my dedicated server. (Fresh Ubuntu 20.04)

I can give you my server details to check what's going on.

**Comment by Donniewr** [comment]
When I installed Cipi the last version was 3.0.10, my panel was updated to 3.1.0 last night but I still can't manage my server.

**Comment by andreapollastri** [comment]
Hi @Donniewr and @josephasmith1!
The Cipi installation script is very "stupid" and during installation process, it will replace "CIPIIP" with your real IP in laravel default DB seeders:
https://github.com/andreapollastri/cipi/blob/4148fa1f650234718daf78110045157986c2d8dc/database/seeders/DatabaseSeeder.php (line 31)

This operation is done into go.sh script: 
https://github.com/andreapollastri/cipi/blob/9d722729e577d446890877c6a32e915cb1b02ea0/go.sh (line 570)
And the real is taken by a curl to AWS: IP=$(curl -s https://checkip.amazonaws.com) (line 8)

If this curs was empty or something else I don't know how work but if you want solve your issue, log in into your Mysql DB and into cipi->servers add manually your server IP into the DB table! 

Sorry but I tryed to install it in many servers and providers and I never had the same problem... what provider are you using?

**Comment by Noaber** [comment]
Maybe it is an idea to manually update the IP in the panel when you see that your IP is still CIPIIP instead of loggin into the MySQL database ?

**Comment by andreapollastri** [comment]
> Maybe it is an idea to manually (click with modal ?) update the IP in the panel when you see that your IP is still CIPIIP instead of loggin into the MySQL database ?

Good Idea! I'll update it ;)

**Comment by Donniewr** [comment]
> Hi @Donniewr and @josephasmith1! The Cipi installation script is very "stupid" and during installation process, it will replace "CIPIIP" with your real IP in laravel default DB seeders: https://github.com/andreapollastri/cipi/blob/4148fa1f650234718daf78110045157986c2d8dc/database/seeders/DatabaseSeeder.php (line 31)
> 
> This operation is done into go.sh script: https://github.com/andreapollastri/cipi/blob/9d722729e577d446890877c6a32e915cb1b02ea0/go.sh (line 570) And the real is taken by a curl to AWS: IP=$(curl -s https://checkip.amazonaws.com) (line 8)
> 
> If this curs was empty or something else I don't know how work but if you want solve your issue, log in into your Mysql DB and into cipi->servers add manually your server IP into the DB table!
> 
> Sorry but I tryed to install it in many servers and providers and I never had the same problem... what provider are you using?


> Maybe it is an idea to manually (click with modal ?) update the IP in the panel when you see that your IP is still CIPIIP instead of loggin into the MySQL database ?


Thanks for the fix, it works. I'm using Nforce.com dedicated servers.


It is possible in the last version to update the IP in the panel if we see CIPIP or it is not implemented yet?
