### ISSUE TITLE
phpMyAdmin 

### ISSUE THREAD

**Issue by sertacdemirtas** [andreapollastri/cipi#271]
Hey,

First of all keep up the good work cipi is awsome!
It would be great if we can access phpMyAdmin through cipi.
Can you integrate phpMyAdmin in future versions ?

Best regards.

**Comment by magix01** [comment]
It was in version 2x but removed intentionally, you can just download phpmyadmin and access it from your domain.

**Comment by andreapollastri** [comment]
Hi! No, phpmyadmin is not still installed by default. Sorry. Use Table Plus or Sequel PRO... or install phpmyadmin by yourself. It is not secure in production servers!
