### ISSUE TITLE
Access Denied When execute sh deploy.sh in terminal

### ISSUE THREAD

**Issue by patricktan98** [andreapollastri/cipi#272]
Hi contributors,

I am testing cipi panel and come across below error when attempting to deploy the code from Git Repository by using generated site user account.
![image](https://user-images.githubusercontent.com/50147719/142155329-e500321d-ab96-4892-ab99-5598fa751bbe.png)

Thanks.

**Comment by andreapollastri** [comment]
Did you update your Cipi SSH into Gitgub?

**Comment by andreapollastri** [comment]
PS... you don't have to use sudo to deploy!

**Comment by andreapollastri** [comment]
I checked and it works... follow the guide and let me know! Thank You
