### ISSUE TITLE
Alias points to wrong basepath

### ISSUE THREAD

**Issue by LemarinelNet** [andreapollastri/cipi#273]
Steps to reproduce :
I created a site.
Then I added an alias.
Then, I updated the basepath : The "/etc/nginx/sites-enabled/cpxxxxxx.conf" is correct. But the alias is not updated, and still points to the previous basepath.

**Comment by andreapollastri** [comment]
I'm checking it! I hope to solve it definitely soon!

**Comment by andreapollastri** [comment]
Hi, a new version has been released... check after the autoupdate (on version 3.1.0) and let me know! Thank You for the issue!

**Comment by andreapollastri** [comment]
Version 3.1.1 is the best solution for this issue... not 3.1.0! let me know if it is solved! Thank You
