### ISSUE TITLE
Nginx Failed to start after requesting SSL on ARM Server

### ISSUE THREAD

**Issue by MangalM5** [andreapollastri/cipi#309]
Hi, I have installed Cipi Control panel on Oracle ARM Server and everything works perfectly.
But, when I request SSL for Domain The Control panel and website refused to connect and I found that Nginx is Failing to start.
So, I manually started NGINX, and everything works. 

But every time I request and most of the time NGINX failed to start. I also tried reinstalling CIPIpanel on the fresh server then also the same problem.

Can you please take a look if the problem can be solved
![Screen Shot 2021-12-10 at 9 50 23 PM](https://user-images.githubusercontent.com/68841832/145606700-ce19d3c6-c702-4000-9cf8-20691bcf5241.png)
?

**Comment by andreapollastri** [comment]
Hi! Thank You for the issue. I'm sorry about the problem. I have to investigate it... can you send me your output of this command?

cat /usr/lib/systemd/system/user@.service

I need to know if [Service] object contains "StartLimitBurst=0" 

Let me know! Thank You
Andrea

**Comment by andreapollastri** [comment]
Try to add:

Restart=always
RestartSec=3s

at the end of the file and let me know if it works! Sorry for this debug asking! ;)

**Comment by MangalM5** [comment]
![Screen Shot 2021-12-10 at 10 16 42 PM](https://user-images.githubusercontent.com/68841832/145610599-c6e5e811-324b-49f6-886d-540213a3b89a.png)

Added above 2 lines but didn't Work. Still the same problem.

**Comment by andreapollastri** [comment]
Ok! Let me check! I'll response when I'll find a solution!

**Comment by MangalM5** [comment]
Ok Sir, Thank You very much for your precious time.

**Comment by MangalM5** [comment]
I don't know but this may help should I try these solutions in the issue.
https://github.com/serghey-rodin/vesta/issues/1874

**Comment by andreapollastri** [comment]
HI! I did several fixes but I can try it only on Digital Ocean and AWS today... check a fresh installation of Cipi new version: 3.1.7 on your VPS and let me know if it's solved... if not I can suppose that is a limit of the provider that we can't override!!!

**Comment by MangalM5** [comment]
Hi.
It worked 2 times but 3rd time I requested SSL the Nginx status show failed.
But the Website & Panel keeps working but Nginx status shows Failed and Nginx start command gives error.
Tried nginx restart it failed too.

This time we are getting a different error.

I have rebooted a System and Now Nginx shows Active.


![Screen Shot 2021-12-11 at 8 18 13 AM](https://user-images.githubusercontent.com/68841832/145661266-03b63c97-6773-4135-ae0e-3ba92420c7b9.png)

**Comment by MangalM5** [comment]
Now It's working I don't know above was actually a problem or not. I requested SSL 3 Times and every time NGINX started and is Active.

But in the above error, Ngixt was working but showing Failed in status.

**Comment by andreapollastri** [comment]
Perfect ;)

**Comment by MangalM5** [comment]
> Hi. It worked 2 times but 3rd time I requested SSL the Nginx status show failed. But the Website & Panel keeps working but Nginx status shows Failed and Nginx start command gives error. Tried nginx restart it failed too.
> 
> This time we are getting a different error.
> 
> I have rebooted a System and Now Nginx shows Active.
> 
> ![Screen Shot 2021-12-11 at 8 18 13 AM](https://user-images.githubusercontent.com/68841832/145661266-03b63c97-6773-4135-ae0e-3ba92420c7b9.png)

Please take a look at this if you can understand why it could have been caused after generating SSL. Nginx was working but showing failed is status comment and could not accept restart, start or stop command.

Thank You
