### ISSUE TITLE
No panel URL after installation

### ISSUE THREAD

**Issue by jimmybisenius** [andreapollastri/cipi#31]
Hey, I'm having some trouble getting Cipi up and running properly with a Google Cloud Compute Engine f1-micro instance with Ubuntu 18.04 LTS installed - could you please help? I've attached a screenshot below for reference.
![screenshot-cipi](https://user-images.githubusercontent.com/6027238/67168770-5e47d580-f375-11e9-8a9e-163a58d9744a.png)

**Comment by andreapollastri** [comment]
It was fixed... I will release the version in next minutes, sorry for the late support... my last months were very hard!
