### ISSUE TITLE
multiple servers and replication

### ISSUE THREAD

**Issue by elpadua** [andreapollastri/cipi#314]
The function of adding multiple servers could be improved, to also add replication, which if I have a website that is heavy, with simple configurations, make the website replicate, or when creating a new website, instead of select a single server to host it, select replication, and that the website is distributed in all my linked servers, of course, the databases would be on a fixed server

**Comment by elpadua** [comment]
that allows to create a platform, that replicates the websites in my entire network of linked servers, and that if it can also distribute the load, with an integrated load balancer

**Comment by elpadua** [comment]
on the subject of databases, also allow to link mysql servers like a normal server, and create databases from cipi

**Comment by andreapollastri** [comment]
Hi! Thank You for the idea... I'll evaluate it for the next version.
Currently, I can say that it's very complex so... it's a good idea but I don't think that I will realize it... Cipi has to be a simple panel for simple projects!

**Comment by elpadua** [comment]
It would be great to customize cipi using some plugin system, and maybe it
would lead to this idea, opening the way to many features and
customizations.
