### ISSUE TITLE
Error installing Wordpress

### ISSUE THREAD

**Issue by Donniewr** [andreapollastri/cipi#315]
Hello,

I'm not sure why but I can't install Wordpress anymore.

"There has been a critical error on this website." While submitting database informations.

Fresh Cipi test install on Linode server.

 thrown in /home/cp8e9a36c79/web/public/wp-includes/wp-db.php on line 2056" while reading response header from upstream, client: 0000, server: test.>
2021/12/11 07:14:01 [crit] 74319#74319: *10 connect() to unix:/var/run/php/php8.1-fpm-cp8e9a36c79.sock failed (2: No such file or directory) while connecting to > to upstream, client: 000, server: test.Mysite.com, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm-cp8e9a

**Comment by Donniewr** [comment]
It works with PHP 8.0 but not 8.1.

Maybe Wordpress is not compatible with 8.1 yet or a bug in Cipi?

**Comment by andreapollastri** [comment]
Hi! Thank You for the issue. I don't know how WP works and I don't use WP but I can say that I'm working within Laravel 8 on PHP 8.1 and MySql 8 managed by Cipi Control Panel without any error! So I think that it's a WP issue, PHP 8.1 is 15-20 days old! I'm happy that you solved with PHP 8.0. Now I'll try to install a brand new WP just for fun and make some check!

**Comment by andreapollastri** [comment]
Hi! I did a fast check: https://wp.cipi.dev/ and I confirm that WP, in my opinion, is not full compatible with PHP 8.1 yet! It runs on PHP 7.4 and PHP 8.0 (not 8.1)

**Comment by Donniewr** [comment]
Thanks, I will use 8.0 for now.

8.1 is causing fatal error during the WP installation only.
