### ISSUE TITLE
502 Bad Gateway - Changing PHP version 

### ISSUE THREAD

**Issue by neo22s** [andreapollastri/cipi#326]
Hello,

When I change the PHP version of any app to lower than 8.1 I get 502 Bad Gateway.

This is a big problem since WP in 8.1 gives lot of problems.

Seems related to:
https://github.com/andreapollastri/cipi/issues/245

CIPI version 3.1.10

**Comment by andreapollastri** [comment]
Hi! If you try to use WP within PHP 8.1 it goes in 502 so, to fix it now you have to:
- change your PHP version to 8.0 or 7.4 
- restart PHP and nginx service into server area (or reboot your VPS)
- last step... NEVER USE WP WITH PHP 8.1 YET... IT'S NOT READY!

Let me know if it's solved!

**Comment by neo22s** [comment]
The problem here is that I have tried to use it also with phpmyadmin and
some custom code and still did not work.

I love the work you are doing. Hopefully soon I can help a bit in the
project. In the meantime I need to use for production another panel. But I
will be keeping an eye on this project 🙏🙏😍

**Comment by andreapollastri** [comment]
Hi! I'm really sorry about this issue... can you give me more information about the error log of your applications?
If you want send me them here or to hello@cipi.sh without any "personal data" so I can understand what happens with your code on my configuration! Thank You for the issue! ;)

**Comment by andreapollastri** [comment]
PS: I'm trying phpmyadmin on PHP 8.1 and it works fine also within huge SQL dumps import!
https://pma.demo-main.cipi.app/

**Comment by andreapollastri** [comment]
PS2: no issues with a brand new WP 5.8.2 installation on PHP 8.0: https://wp.demo-main.cipi.app/ (issues on PHP 8.1).
I don't use WP but currently I have four Laravel 8 projects in production on CIPI and PHP 8.1 and I have not any problem. 
Please, if you want, help me to improve Cipi with your errors log / info about the code you are running on it!

Thank You
Andrea

**Comment by neo22s** [comment]
Hello,

Maybe I am not explaining hehe

With a clean installation works good. But when you change to a different
php version then you get the error. It's the same as reported in the issue
I have linked in the description ;)

**Comment by andreapollastri** [comment]
Hi! Thank You for the feedback. I did a check and you are right! I fixed PHP switch in version 3.1.11... if you have an active Cipi server it will be update tonight, if you make a brand new installation it comes with new version! 
If you want check this new version and let me know if this issue is solved. Thank You!

**Comment by andreapollastri** [comment]
PS: to see the fix... you have to recreate any current 502 bugged site on new Cipi version! Sorry!

**Comment by neo22s** [comment]
Thanks a lot! I will try next week's I guess I had to do a migration. And I
ended up using runcloud... I was on a hurry.

I love this project and I have many ideas hehehe hopefully I will have some
time to share with you. Again congrats

**Comment by andreapollastri** [comment]
Thank You! ;)
