### ISSUE TITLE
New sites directory not created.

### ISSUE THREAD

**Issue by Donniewr** [andreapollastri/cipi#330]
Hello,

I installed Cipi on my clean Ubuntu 20.04 server, after the installation I could not manage the server but changing the IP in the database worked.

https://github.com/andreapollastri/cipi/issues/270#issuecomment-990763402

But when I create a new site, the website is created on the panel but no directory/users is created on the server.

My domain is showing "This domain/subdomain is not configured on this server".

**Comment by Donniewr** [comment]
I'm now getting errors on my panel after I changed the root cipi user password.

![Screenshot 2021-12-15 144311](https://user-images.githubusercontent.com/95908882/146197353-bd273b57-87d2-4e05-80f7-21d21fdbf0f9.jpg)
![Screenshot 2021-12-15 144051](https://user-images.githubusercontent.com/95908882/146197057-ea97f1db-075a-43e7-86ef-c3371761aa64.jpg)

**Comment by Donniewr** [comment]
I found the issue, it happen when the server is missing dependencies.

To fix this we have to run this command before installing Cipi.

apt-get -y install software-properties-common curl wget nano vim rpl sed zip unzip openssl expect dirmngr apt-transport-https lsb-release ca-certificates dnsutils dos2unix zsh htop ffmpeg

I think CIPI is trying to use Curl during the installation but it was not installed yet, it create this issue 

https://github.com/andreapollastri/cipi/issues/270#issuecomment-990763402

**Comment by cynicalsam** [comment]
I am having the same issue. Curl isn't installed by default in the image on my VPS. This means the $IP variable isn't being filled in.  Installing Curl before running the install script resolves the issue. May be worth adding a check for Curl at the top of the install script so prevent this happening in future

**Comment by andreapollastri** [comment]
Hello! Thank You for this issue and Thank You @Donniewr for the investigation! The issue has been solved in v3.1.13 (released some minutes agos). I'm really sorry for the inconvenience... Let me know if it works! Best. Andrea

**Comment by cynicalsam** [comment]
Yep works perfectly!

Thanks for the swift fix
