### ISSUE TITLE
Root login after Cipi installation

### ISSUE THREAD

**Issue by Donniewr** [andreapollastri/cipi#337]
Hi,

Is it possible to allow root login after installation? The default cipi user don't have enough power for me. I can't access backups from automysqlbackup and can't download logs files using Filezilla. it's frustrating.

**Comment by andreapollastri** [comment]
Hi! Cipi disables by default root login so you cannot SSH into your server using: 

`ssh root@YOUR-IP`

but you have to use:

`ssh cipi@YOUR-IP `

than: `su root` or `sudo commands` (cipi is a sudoer)

anyway if you need to restore root login you can login into SSH as "cipi" and run:

```
sudo rpl -i -w "PermitRootLogin no" "PermitRootLogin yes" /etc/ssh/sshd_config
sudo service sshd restart
```

Let me know if it's solved! 
Best

Andrea

**Comment by Donniewr** [comment]
Thanks! This is is so much better for me to use root instead of sudo/changing permissions.
