### ISSUE TITLE
Cron jobs can't be removed.

### ISSUE THREAD

**Issue by Donniewr** [andreapollastri/cipi#341]
Hello,

I have added a cron job using the panel but it can't be removed, when you remove it and reload the page the cron job is still present.

I even tried root crontab -e and It re-appear every time.

Thanks,

**Comment by andreapollastri** [comment]
Hi @Donniewr! You are right... if you delete everything in "cron editor", the patch API doesn't update your server so you have to leave at list a blank space. Thankyou for the issue, I'll fix it in next versions. Let me know if with a white space it works! Best, Andrea

**Comment by Donniewr** [comment]
Yes it works, I just added a random number. It updated.

Thanks,
