### ISSUE TITLE
WebScokets support

### ISSUE THREAD

**Issue by punyflash** [andreapollastri/cipi#342]
Would be nice to have ability to add WebSockets servers such as [Soketi](https://github.com/soketi/soketi), which basically a self-hosted Pusher protocol. Their API seems to be well scalable and may be nicely integrated in control panel ecosystem. For now, I host it as a separate docker image on my server.

Love your product by the way, saved weeks of work for me <3

**Comment by andreapollastri** [comment]
Hi, Thank You for the idea... currently it's not in the roadmap but I'll evaluate it for the next versions and if it's useful and simple to manage I'll integrate a WebSockets feature. Best. Andrea
