### ISSUE TITLE
Installer apt-get issue

### ISSUE THREAD

**Issue by magix01** [andreapollastri/cipi#343]
Hi Andrea,

I have noticed this strange issue when installing cipi on newly initialized servers, some providers on server init first run do the apt-get update/upgrade and the process is running in background, if the process is still in background when you init cipi install, the install will go through but fail in background (apt-get process locked), in panel the server is there, however nginx, sql and other services are not installed, then server wipe/reinstall is needed to reinit cipi again.

Possible solution:

1. Check if there is apt-get process running in the background before init of cipi installer, if throw error?
2. Check if there is "restart required" linux motd/flag before init of cipi installer.
3. (dirty) Kill apt-get background processes before installing cipi?

This should fix the installation problems i had, i think digitalocean does not do this, but other providers i have tested the panel with work, they use 20.04 and cipi works perfectly but are somehow finicky.

Regards

**Comment by andreapollastri** [comment]
Hi! Thank You for the issue... what provider are you using? I never found this problem and I have to replicate it!

**Comment by magix01** [comment]
Try vsys.host and shinjiru, regards

**Comment by andreapollastri** [comment]
Hi @magix01, I'm really sorry but I think that the required providers have custom repositories about Ubuntu and its vendor so I could not change the installer in that way because it may break installation process in major providers (aws, digital ocean, etc...). I'm sorry!

**Comment by magix01** [comment]
I dont think its custom repo, they just run apt-get upgrade on first init to update their old distro packages on the image they put.
