### ISSUE TITLE
Database & SSH username.

### ISSUE THREAD

**Issue by Donniewr** [andreapollastri/cipi#345]
Hello,

In the 3.1.8 release note it said "Configurable users and db/path naming prefix"

How can we use this? I'm using cipi to manage multiple websites and it can be confusing because all the users details looks the same. It would be a nice improvement if we could choose the Database name/users and also the username of the SSH user. Maybe the SSH user should be the name of the site without the domain extension?

**Comment by andreapollastri** [comment]
Hi, you are talking about the "User Prefix" feature that has been implemented into app/cipi.php config (https://github.com/andreapollastri/cipi/blob/master/config/cipi.php).
Adding `CIPI_USERS_PREFIX=your-prefix` into .env file and running `php artisan config:cache`, you can change the global user prefix from cp to your-prefix. So, this is not helpful to your needs but it was required from some provider that is implementing Cipi to customize and brand the panel. 

I'm sorry but, currently, is not possible to differently naming sites.
