### ISSUE TITLE
Deleting Alias not working neither Domain Change in Basic Information

### ISSUE THREAD

**Issue by MangalM5** [andreapollastri/cipi#346]
Hi,
I am on the latest version 3.1.14 and using Oracle ARM Server.
Everything was working fine.
But I just added non www domain alias and issued an SSL certificate but SSL was not issued for the alias domain and now when I tried to delete the alias is says loading progress but does not delete the alias. I also tried editing the domain name in Basic Information but it keeps the same domain after refresh.

I don't know if only I am getting this problem. Please check.
Thank You

Edit: Now when I open the alias domain I get **Domain/Subdomain not configured on this Server!** but in alias, Domain is added.

**Comment by Donniewr** [comment]
There are issues with Oracle/ARM servers currently.

https://github.com/andreapollastri/cipi#installation-note

**Comment by andreapollastri** [comment]
Hi! Unfortunately, Cipi has several issues on Oracle ARM. It works fine on AWS, Digital Ocean, Vultr and many other Providers! Sorry for the issue... I'm working to Oracle VPSs support!

**Comment by MangalM5** [comment]
Thanks..
