### ISSUE TITLE
My panel stopped working after few days.

### ISSUE THREAD

**Issue by Donniewr** [andreapollastri/cipi#347]
Hello,

My panel was working perfectly but now creating new sites no longer works. When I create a site on the panel nothing is created on the server.

What is causing this issue? I have not done anything on the server. I just rebooted it.

**Comment by Donniewr** [comment]
I have found the issue, this is because of wrong permissions.

The directory in /var/www/html changed it's permission to www-data:www-data instead of the default www-data:cipi.

I have run this command and rebooted my server to fix the issue: sudo chown -R www-data:cipi /var/www/html

I think it might be a bug in Cipi.

**Comment by andreapollastri** [comment]
Hi @Donniewr , Thank You for the issue... you are right. I fixed it in Version 3.1.15 and it will be auto-installed on your server tonight via cron job. Let me know if you will have future similar issues. Thank You. Andrea

**Comment by mucan54** [comment]
This error happens for me again.

**Comment by mucan54** [comment]
I changed ssh cp user password manually, so it cannot do anything, how I can fix.

**Comment by mucan54** [comment]
I fixed, with generating new password from panel, and then updating current cipi user's password with the generated one.
