### ISSUE TITLE
Can not access my github repo

### ISSUE THREAD

**Issue by mucan54** [andreapollastri/cipi#351]
When I run this codes manually it works : 

```
SSH_KEY="/home/cp62125aca2/git/deploy"
cp62125aca2@MucanWeb:~/web$ ssh-add $SSH_KEY
Identity added: /home/cp62125aca2/git/deploy (git@github.com)
cp62125aca2@MucanWeb:~/web$ git clone git@github.com:Kaffe-Software/CvApp-Backend.git
```

but when I try to use it with 

```
cp62125aca2@MucanWeb:~/web$ sh /home/cp62125aca2/git/deploy.sh
Agent pid 5273
Identity added: /home/cp62125aca2/git/deploy (git@github.com)
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.
```

it doesnt work. I have 2 sites with same repo on different branches. Deploy script works for my other site which is on main branch, but it doesnt work for staging branch.

**Comment by andreapollastri** [comment]
Hi! I can't replicate the issue... I tried to follow Cipi Docs steps to configure GitHub repositories into sites and it works.
Why did you run the first part of commands related to ssh key? 

I have tried several time and in different server this function and I haven't any issues!
