### ISSUE TITLE
Error: Timed out while waiting for handshake SSH to Sites

### ISSUE THREAD

**Issue by ausittechdirect** [andreapollastri/cipi#353]
I am having issues with SSH to sites. 

Ever time I try to access I get the above error. 

Tried restarting the Server but no luck.

**Comment by andreapollastri** [comment]
Hi! What OS and SSH/sftp client Are you using?

**Comment by ausittechdirect** [comment]
Hi! 

Ubuntu 20.04 and tried Filezilla and Codeanyware

**Comment by andreapollastri** [comment]
Ok! I can say that I have no error on filezilla using port 22 and a sftp connection!

Check the ssh key paring of your host into your computer, check any timeout setting into your local ssh2 configuration and check if your vps / provider applies any firewall rule on port 22.

I’m using Cipi on different server and I never had SSH connection issues. I think that your case is a client issue, not server issue!
