### ISSUE TITLE
Is it possible to edit the Holding page and User credentials PDF Branding 

### ISSUE THREAD

**Issue by ausittechdirect** [andreapollastri/cipi#354]
Wondering is it is possible to remove the CIPI branding from these pages.

**Comment by andreapollastri** [comment]
Hi! If you need to do it... you can login into ssh as "cipi" and edit this file: /var/www/html/resources/views/pdf.blade.php.

Than:

cd /var/www/html

And:

php artisan view:cache

Best,
Andrea
