### ISSUE TITLE
Alias Domain SSL Config goes into default conf

### ISSUE THREAD

**Issue by WorksDev** [andreapollastri/cipi#359]
If I assign an alias to a domain and request an SSL certificate for all domains, the SSL configuration is written to the default config - where it potentially does not belong. Also, technically speaking, no further configuration should be created for the alias, but only the server_name of the original domain should be extended.

**Comment by andreapollastri** [comment]
Sorry but I can not follow you! 
Any alias has its nginx config with its SSL cert... there are no issue in aliases and SSLs. Best. Andrea

**Comment by WorksDev** [comment]
> Sorry but I can not follow you! Any alias has its nginx config with its SSL cert... there are no issue in aliases and SSLs. Best. Andrea

Ok to make it clear:
- i created a domain -> fubar.com
- requested ssl cert
- added new alias www.fubar.com
- requested ssl cert

Expected in my Opinion:
- alias www.fubar.com is in configuration of fubar.com or in different single configuration as u said - ssl configuration also

What happens on my side:
- symlink of fubar.com in sites-enabled is deleted, file with ssl content is created
- no separat file for www.fubar.com is created
- ssl configuration of www.fubar.com is now in /etc/nginx/sites-available/default

**Comment by andreapollastri** [comment]
Ok thank you for the detail! I'll check this flow and I'll update this issue in next days!
