### ISSUE TITLE
Servers -> Restart Nginx is not working

### ISSUE THREAD

**Issue by fatihalp** [andreapollastri/cipi#360]
I worked nginx vhosts for hours then I realase that nginx restart is not working from server panel. Manually running "sudo systemctl restart nginx.service" is working from ssh.

**Comment by fatihalp** [comment]
Also thanks for this wonderfull project @andreapollastri

**Comment by andreapollastri** [comment]
Hi! I checked it and it seems work! How do you recognize that it doesn't work from panel? I have to rebuild the issue to find a solution!

**Comment by fatihalp** [comment]
I've changed vhosts many times and didn't reflected to system

**Comment by fatihalp** [comment]
How you testing yourself?

**Comment by fatihalp** [comment]
Maybe my bad @andreapollastri thanks a lot I'm gonna try again. 

I'm thinking backup and migration from x features to move cipi entirely. Using CWP in several server. It's not stable after 5 years. 

I think you have plans to do that. Is it possible to develop modules?
