### ISSUE TITLE
Problema com CIPI

### ISSUE THREAD

**Issue by ciahype** [andreapollastri/cipi#363]
Olá, me chamo Hiago 
Não estou conseguindo excluir site e nem adicionar novos servidores!

**Comment by andreapollastri** [comment]
Hi... can you write in English? I can't understand your lang!

**Comment by ciahype** [comment]
Hi, my name is Hiago
I'm not able to delete site or add new servers!

**Comment by andreapollastri** [comment]
Ok! Give me some more information... What version are you using? These function worked before today?!? Other functions are working? Did you customize something? 

Your errors have no know history and my test and prod panels are running well! 

Give me more details! Currently I can't help you!

**Comment by ciahype** [comment]
I'm using version 3.1.15.
I don't know if they worked before first time using this tool.
I didn't customize anything.
other than that, yes it works.

**Comment by ciahype** [comment]
after I put the custom URL of the server that these functions stopped working!

**Comment by andreapollastri** [comment]
Where did you put an IRL? In server detail or in settings?

**Comment by andreapollastri** [comment]
*URL

**Comment by ciahype** [comment]
in the settings inside the panel!

**Comment by ciahype** [comment]
Is there any way to install the previous version?

**Comment by andreapollastri** [comment]
Ok, and now everything works but not delete site and add new server right? Are you using the panel by ip or by the new url? Did you generate a ssl cert for that url?

**Comment by andreapollastri** [comment]
So you had version 2 before on the same server?

**Comment by ciahype** [comment]
I can add more I can't delete.
access via the new URL.
No, the installation was clean!

**Comment by ciahype** [comment]
the server was cleaned before installing CIPI

**Comment by andreapollastri** [comment]
Ok! Let me check! To help you I have to replicate the error but I don't have errors in all my panels!

What provider are you using that I'll try on that VPS type! Also if is very strange this issue!

When you click delete do you receive any error message or do you have any JS error in console? 

Currently I don't have any element  to understand what happens in you case!

**Comment by ciahype** [comment]
Want dashboard access to see errors?

**Comment by andreapollastri** [comment]
No no, I don't want private data! I have to replicate the error on a my own system! I'll try to create a vps on your provider! What provider are you using?

**Comment by ciahype** [comment]
AWS

**Comment by andreapollastri** [comment]
Ok! I have an operative vps there! Now I try to make a new installation! In the meanwhile check if port 443 is open (was doesn't open it by default). I will check and I'll update this issue in next hours! Thank you for the issue

**Comment by ciahype** [comment]
ports 80, 443 and 22 are open!

**Comment by ciahype** [comment]
I thank you for your attention to my problem!

**Comment by fatihalp** [comment]
Better to have issue templetes @andreapollastri 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by andreapollastri** [comment]
Hello @ciahype! I've checked Cipi on Aws ec2 and on aws lightsail installing it several times and using it for hours and I didn't found any error! I'm really sorry but I can't help you in this case!
If you want, send me your panel credentials (set a temp pwd) via mail at hello@cipi.sh but I don't like to manage other people credentials so if you can avoid I'll be happy! Let me know!  


@fatihalp thank you for the suggest! I'll add it soon!

**Comment by ciahype** [comment]
Find out where the error was.
the error was that i was changing the php version of the application thinking i was changing the php version of the website i had.

I redid the installation without changing the php and there was no error!

**Comment by ciahype** [comment]
I've tried several times, but I get the error:  **The given credentials do not match any records.**

**Comment by ciahype** [comment]
I tried in many ways!

**Comment by andreapollastri** [comment]
Hi! You are right! Mobile Application is not updated to new Cipi Version! @ChristianGiupponi is working on it and we have to wait Google play approvements to publish a new release!
