### ISSUE TITLE
Remove Node.js

### ISSUE THREAD

**Issue by Donniewr** [andreapollastri/cipi#368]
Hello,

Is it possible to remove Node.js from my server without breaking anything? I'm using CIPI for Wordpress and other PHP apps and I don't need it. 

I also get "The deferred dom node could not be resolved to a valid node" sometimes in the browser console on my sites. This is caused by nodejs.

Thanks.

**Comment by andreapollastri** [comment]
Hi! Node is installed but not exposed as "server". It is installed to run npm commands.

Anyway, if you want remove it, run:

sudo apt remove nodejs
sudo apt purge nodejs
sudo apt autoremove
