### ISSUE TITLE
Blank page after fresh, succesfull installation through Documentation suggested method

### ISSUE THREAD

**Issue by RVL-Solutions** [andreapollastri/cipi#370]
I did the installation on a fresh new Ubuntu 20.04 LTS VPS hosted by Contabo. 
I followed the instructions from the Documentation, using the ` wget -O - https://cipi.sh/go.sh | bash` method.

But when I navigate to the given url (public IP) I get a blank page.
Debug console tells me `500 Internal Server Error`

The ssh console shows (deducted sensitive details);

```***********************************************************
                    SETUP COMPLETE
***********************************************************

 SSH root user: cipi
 SSH root pass: <snip>
 MySQL root user: cipi
 MySQL root pass: <snip>

 To manage your server visit: http://<public IP>
 and click on 'dashboard' button.
 Default credentials are: administrator / 12345678

***********************************************************
          DO NOT LOSE AND KEEP SAFE THIS DATA
***********************************************************```

**Comment by andreapollastri** [comment]
Hi! Thank you for the issue, I'm sorry to hear it! Can you share me the error log that you can find at: var/www/html/storage/logs/laravel.log?

Thank You

**Comment by RVL-Solutions** [comment]
Unfortunately, there seems to be no such file within that directory!

Could that be due to me rebooting the VPS in the meantime? If so, I'll gladly reset the VPS and try installing again.

**Comment by RVL-Solutions** [comment]
I think I figured out what went wrong. I vaguely remembered seeing something about failing to get some GPG key, so when scrolling through the install script I tried adding the PPA manually and there it was; Timeout error on obtaining the GPG key.

Reset the VM, started fresh and ran script again.
So far so good. Will keep you updated.

**Comment by andreapollastri** [comment]
Hi! Contabo always gave me Issues with Linux repositories, I think that it is using custom repos. So I'm sorry if the installation process is not perfect! If Cipi works I'm happy... Cipi has been tested on Contabo in v3.0 (php8 not 8.1) and it worked. I suppose that their repositories for PHP8.1 are not stable or ready yet! Sorry. It's not a Cipi problem... I hope that Contabo will adapt its system to a standard such as digital ocean, aws, linode, etc... 
Done!

**Comment by andreapollastri** [comment]
Ps... anyway thank you for the support and the check about this problem! I think that you installation is OK but I suggest to you to set PHP 8.0 to server and sites (not 8.1 for the report that you pasted here).
If you want check if the system has any error, you have to monitor 
/var/www/html/storage/logs/laravel.log file! If it is missed, you have no errors!
