### ISSUE TITLE
base path update error : not updating sites-enabled

### ISSUE THREAD

**Issue by ubxty** [andreapollastri/cipi#378]
Updating a base path for a domain , updates it in sites-available , but not in sites-enabled . if not updated in sites-enabled , nginx will not read the updated path,

Also add an option to restart nginx after updating the path , as restart is required for the path changed to be effective

**Comment by andreapollastri** [comment]
Thank you for the issue, I'll check this case in next hours!

**Comment by andreapollastri** [comment]
I don't have the same issue! Are you sure about it? What provider are you using? And what version of cipi? 

The only case that does not change is if you try to leave it blank for an api patch issue that I will solve soon... in other cases it works!
