### ISSUE TITLE
cipi Android app: Unable to Login 

### ISSUE THREAD

**Issue by ubxty** [andreapollastri/cipi#380]
Tried all possible username , password / domain combinations 
Unable to login

**Comment by andreapollastri** [comment]
Hi @christiangiupponi is working to solve it! It's not my repository! Sorry... we have to wait!

**Comment by ubxty** [comment]
@ChristianGiupponi Any plans on making the Mobile App opensource ?

**Comment by cgiupponi** [comment]
Hi @ubxty yes the app will be open source asap!  
Which version of cipi are you using?
