### ISSUE TITLE
Cleaner Account naming

### ISSUE THREAD

**Issue by ubxty** [andreapollastri/cipi#382]
While creating a new site , the username generated is random , Instead use a cleaner name generation based on domain/site 

For eg: If site is beta.sample.com => name the account as betasamplecom and ssh login is betasamplecom@192.168.1.1

**Comment by Donniewr** [comment]
I'm requesting this feature too.

https://github.com/andreapollastri/cipi/discussions/376

**Comment by Noaber** [comment]
Correct me if I am wrong, but @andreapollastri said that the random names is there for security (not guessable)

**Comment by andreapollastri** [comment]
Hi! 
In my opinion... Username has to be unique and not refered to site domain (that can be changed).
So I prefer to leave the randrom username that generate an unique and secure username for devs.

**Comment by dhpowrhost** [comment]
At least the possibility to chose the username your self would be a great option. just a tick-box: custom username; and then a text field with the custom username, and then db, username path etc. will be the same as that custom username. Should be really simple to implement
