### ISSUE TITLE
php opcache

### ISSUE THREAD

**Issue by ubxty** [andreapollastri/cipi#384]
Ability to enable / disable php opcache from the admin , to speedup the website operations

**Comment by ubxty** [comment]
@Donniewr It should be optional for user to enable / disable , as it creates an issue with development servers when the code changes donot reflect , unless the user has restarted the fpm

**Comment by andreapollastri** [comment]
Hi! The cache has been integrated to support code changes in a short time, I work with it every day and I never had any issue.... anyway I would like to leave cipi a simple panel for devs!
