### ISSUE TITLE
Security : ssh key based login for domain accounts 

### ISSUE THREAD

**Issue by ubxty** [andreapollastri/cipi#387]
Only the root/cipi account should be accessible using password , rest all accounts should only be accessible via ssh key

**Comment by andreapollastri** [comment]
Hi, I don't agree... site accounts are limited, cipi account is "root", so maybe SSH key could be on cipi user and other limited site users can use password.

Anyway I would like leave cipi a simple panel for all developers and password is more simple than ssh key to use!
