### ISSUE TITLE
Cipi Webapp security 

### ISSUE THREAD

**Issue by ubxty** [andreapollastri/cipi#388]
The webapp and api needs an enhanced security .
Consider using passport as authentication provider .

**Comment by Donniewr** [comment]
A brute force protection on the Cipi login page would be a good thing too.

**Comment by ubxty** [comment]
@Donniewr Yes and laravel natively support rate limiting , so those features can be used

**Comment by andreapollastri** [comment]
Hi this function is used and Cipi uses JWT standards! Anyway I'm v4 It will use Laravel Jetstream! So wait for new release!
