### ISSUE TITLE
Accessing the server IP using HTTPS redirect to website.

### ISSUE THREAD

**Issue by Donniewr** [andreapollastri/cipi#389]
Hello,

If you access the server IP using HTTPS you are redirected to the first website you added to the server, expected or a bug?

Example: `https://123.123.124.10  ==>> https://mysite.com`

I found this bug while looking at my website logs.

Thanks,

**Comment by andreapollastri** [comment]
Hi! it's an organic behavior 
! IP does not support https and Cipi (as cpanel and similar) returns the first https site! If you want use https with cipi  you have to assign a panel domain and generate let's encrypt from panel!
