### ISSUE TITLE
Server error Missing Authorization.

### ISSUE THREAD

**Issue by 0x0undefined** [andreapollastri/cipi#392]
I have same problem as #248  i dont know how to fix it.

System Error
Ops! Something went wrong... try later!

and in console i found this:
`{"message":"Authorization header missed in payload.","errors":"Missing Authorization."}`

It happened after changing the server ip and rebooting

**Comment by 0x0undefined** [comment]
I don't know how, but it magically fixed itself but i have another issue...

When I create a page in a panel, the user of that page is not created.

**Comment by Donniewr** [comment]
> I don't know how, but it magically fixed itself but i have another issue...
> 
> When I create a page in a panel, the user of that page is not created.

Look like you got the same issue I had.

Check how I fixed it here:
https://github.com/andreapollastri/cipi/issues/347

**Comment by andreapollastri** [comment]
Maybe temporaneily your JWT token has been expired! Re-login to fix it!
