### ISSUE TITLE
Ssl and Cron is not working

### ISSUE THREAD

**Issue by vimal-360** [andreapollastri/cipi#395]
Can not generate ssl certificate using click button. also I added my laravel path config in crontab still not running cron.

**Comment by Donniewr** [comment]
SSL is working for me, make sure to point your domain to the server IP and to disable Cloudflare (Gray cloud).

Cronjob on the CIPI interface are using the root user. Try adding the job using your app SSH user instead.

**Comment by vimal-360** [comment]
I did all the things like reboot. recheck nameserver etc. still SSL is not generating.
@Donniewr Do you mean the per site ssh user? I did add using cipi admin panel.

**Comment by vimal-360** [comment]
@Donniewr I did manually ssl certificate using certbot - nginx now its working. also crontab -e is works. now I ma facing alias  issue. I have x.com.au domain. but for alias www.x.com.au not working. I tried restarting nginx also.  :)

**Comment by Donniewr** [comment]
> @Donniewr I did manually ssl certificate using certbot - nginx now its working. also crontab -e is works. now I ma facing alias issue. I have `x.com.au` domain. but for alias `www.x.com.au` not working. I tried restarting nginx also. :)

Alias works for me, did you add a DNS record (CNAME) for the www domain?

**Comment by andreapollastri** [comment]
Hi! I checked current version of Cipi and I don't have any issue with cron or SSL features!
