### ISSUE TITLE
Default login not working

### ISSUE THREAD

**Issue by Kirby-Peter** [andreapollastri/cipi#397]
When I'm on the control panel to login after an install the default username "administrator" and password "12345678" doesn't work.

![image_2022-03-12_001304](https://user-images.githubusercontent.com/65928651/158004821-f9071f35-79e1-47c3-8f0f-a7d8246625d3.png)

**Comment by Kirby-Peter** [comment]
just wanted to know if I was missing something

**Comment by andreapollastri** [comment]
Hi! I think that something went wrong during installation process! Did you have any error in setup process?

**Comment by Dikoper** [comment]
> Hi! I think that something went wrong during installation process! Did you have any error in setup process?

Hi. No, there was only couple warnings about some package install (cant remember which), but script contunue installation

**Comment by gorfreed** [comment]
I have to confirm. Cipi install is currently not working. I tried on two different machines with the same result: After a very lengthy installation process (seriously, ALL php versions + their extensions need to be installed?), it is impossible to log into the Dashboard with the credentials "Administrator" / "12345678".
