### ISSUE TITLE
ssh: connect to xxx.xxx.xxx.xxx port 22: Connection refused

### ISSUE THREAD

**Issue by vimal-360** [andreapollastri/cipi#400]
I created new site now I can not connect existing user credentials.

I restarted Droplet many times. now I also can not connect using ssh cipi@ip.

Ssl not working, Cron not working. so much buggy system.

**Comment by andreapollastri** [comment]
Hi! I'm really sorry to hear about this issue! me and other 5000+ users are using Cipi on several servers without issues! 
Your issue seems a firewall lock... what provider are you using? check if it's limiting your access to 22 port!

**Comment by vimal-360** [comment]
I am using Digital Ocean and all firewall config is ok.

**Comment by HomaEEE** [comment]
Some error after reboot VPS, 22 port is open
