### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by ririko5834** [andreapollastri/cipi#401]
Add email hosting, DNS hosting (that you can set nameservers for your domain/subdomain and manage records on cipi), Mysql, PostgreSQL, Mongo and Redis databases (they should be optional, when enabled cipi should auto create database and database user for your website), built-in file editor

**Comment by andreapollastri** [comment]
Hi! Cipi does not have this scope. You have to use cPanel or Plesk if you need a "full stack" email, dns and web panel! Cipi is a panel for websites only within a simple LEMP + redis stack (not mongo or PG).
