### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ririko5834** [andreapollastri/cipi#402]
When I try to login with default credentials
![image](https://user-images.githubusercontent.com/64729293/160138349-48ef7f5e-c92e-4a85-b750-f2d573fa13ef.png)

After running install command second time 
![image](https://user-images.githubusercontent.com/64729293/160138531-b3096532-705a-472a-8b21-0bcb58cf3e1c.png)

Ubuntu 20.24, arm-based CPU instance from oracle

**Comment by dfag86** [comment]
I have the same.  Clean installation on something Ubuntu, all ok. Enter default login credentials and error.  Login is not working.

**Comment by Donniewr** [comment]
Oracle server are not supported.
https://github.com/andreapollastri/cipi#installation-note

**Comment by andreapollastri** [comment]
Oracle is different than any other standard cloud provider (such as AWS, Digital Ocean, Azure, etc...) so Cipi will not support it! Sorry!
