### ISSUE TITLE
the project is still active?  

### ISSUE THREAD

**Issue by ivan-vilches** [andreapollastri/cipi#408]
the project is still active?   do you use with production sites? thanks you

**Comment by Donniewr** [comment]
Yes I use CIPI on 3 production sites. I hope @andreapollastri is planning on updating the project soon to support Ubuntu 22.04 LTS.

**Comment by dfag86** [comment]
> Yes I use CIPI on 3 production sites. I hope @andreapollastri is planning on updating the project soon to support Ubuntu 22.04 LTS.

Currently, the installation is not working and the support does not exist, so I will not risk the production pages.

**Comment by Donniewr** [comment]
> > Yes I use CIPI on 3 production sites. I hope @andreapollastri is planning on updating the project soon to support Ubuntu 22.04 LTS.
> 
> Currently, the installation is not working and the support does not exist, so I will not risk the production pages.

It works for me, what is your server provider? I use it on a dedicated server, Linode and another provider without any issues.

**Comment by dfag86** [comment]
> > > Yes I use CIPI on 3 production sites. I hope @andreapollastri is planning on updating the project soon to support Ubuntu 22.04 LTS.
> > 
> > Currently, the installation is not working and the support does not exist, so I will not risk the production pages.
> 
> It works for me, what is your server provider? I use it on a dedicated server, Linode and another provider without any issues.

with different operators, I tried something with three.  Installation ok and then the default login details are not working.

**Comment by Donniewr** [comment]
> > > > Yes I use CIPI on 3 production sites. I hope @andreapollastri is planning on updating the project soon to support Ubuntu 22.04 LTS.
> > > 
> > > 
> > > Currently, the installation is not working and the support does not exist, so I will not risk the production pages.
> > 
> > 
> > It works for me, what is your server provider? I use it on a dedicated server, Linode and another provider without any issues.
> 
> with different operators, I tried something with three. Installation ok and then the default login details are not working.

That's weird, maybe it's something related to your keyboard language or something like that. Try copy pasting the login details. Also check your browser console on the login page and look for errors.

**Comment by dfag86** [comment]
> > > > > Yes I use CIPI on 3 production sites. I hope @andreapollastri is planning on updating the project soon to support Ubuntu 22.04 LTS.
> > > > 
> > > > 
> > > > Currently, the installation is not working and the support does not exist, so I will not risk the production pages.
> > > 
> > > 
> > > It works for me, what is your server provider? I use it on a dedicated server, Linode and another provider without any issues.
> > 
> > with different operators, I tried something with three. Installation ok and then the default login details are not working.
> 
> That's weird, maybe it's something related to your keyboard language or something like that. Try copy pasting the login details. Also check your browser console on the login page and look for errors.
> 
> Also Oracle and arm server are not supported.

yes, it is strange, but I was not the only one with such a problem.  I reported it here on another thread along with another person and silence.  There was no response.  There were no typos or blank characters.  Everything is checked and copied straight away.

**Comment by Noaber** [comment]
@andreapollastri : Is this project still in active development ?

**Comment by andreapollastri** [comment]
Yes! I have been very busy with my main job but Cipi 4 will be released soon! Sorry for the late!

PS: oracle will be not support! It's not a standard configuration as AWS, Digital Ocean, Vultr, Linode, etc... so I'm sorry but I can't modify everything everytime for Oracle issues!

**Comment by ivan-vilches** [comment]
can you add client users? i wish my client an manage his sites
