### ISSUE TITLE
Default Login not working after Installation (#397 

### ISSUE THREAD

**Issue by gorfreed** [andreapollastri/cipi#411]
I have to confirm #397 as not resolved. Cipi install is currently not working. I tried on two different machines with the same result: After a very lengthy installation process (seriously, ALL php versions + their extensions need to be installed?), it is impossible to log into the Dashboard with the credentials "Administrator" / "12345678".

**Comment by andreapollastri** [comment]
Are you using administrator / 12345678 or Administrator / 12345678?
