### ISSUE TITLE
Database (MySQL) on an external host

### ISSUE THREAD

**Issue by PudlatyPL** [andreapollastri/cipi#413]
Hello, I have question associated with the panel. How to set on external database? I changed mysql addres on .env but nothing has changed, the panel still uses the old one

**Comment by Alnaggar94** [comment]
@PudlatyPL 
I'm looking for the same, have you found a solution?

**Comment by PudlatyPL** [comment]
> @PudlatyPL 
> I'm looking for the same, have you found a solution?

No

**Comment by andreapollastri** [comment]
Hi! No, Cipi, for security reasons, doesn't let to expose 3306 port externally but you can connect your external client to your DB via SSH tunnel.

Anyway... If you want to open 3306, you can do it manually:

sudo ufw allow 3306/tcp
sudo nano /etc/mysql/mysql.conf.d/mysqld.cnf
Than...Update bind-address = 127.0.0.1 to bind-address  = 0.0.0.0 and Save it!
sudo service mysql restart
Now your MySql Server is ready to connect from anywhere by your username and password.
