### ISSUE TITLE
What system does cipi support

### ISSUE THREAD

**Issue by itzdrli** [andreapollastri/cipi#416]
hi, i wanna try cipi panel, but when i check the document, it says only supports ubuntu 20.04?
Does cipi supports other systems like debian 10/11 or ubuntu 22.04 and more?

**Comment by Alnaggar94** [comment]
As I know it only support Ubuntu 18, and 20

**Comment by Donniewr** [comment]
Only 20.04 but the project author said he is working on 22.04 support. he said June.

**Comment by Alnaggar94** [comment]
> Only 20.04 but the project author said he is working on 22.04 support. he said June.

We didn't hear anything from him since June, I hope he is doing well.

**Comment by Noaber** [comment]
Hope so indeed!

it's been quiet since May.

**Comment by andreapollastri** [comment]
Hi! Cipi v4 will be realesed soon and it will support Ubuntu 22.04!
