### ISSUE TITLE
Installation success but gives home directory

### ISSUE THREAD

**Issue by kingmaster772** [andreapollastri/cipi#432]
Accessing my IP give me cipi home directory. How to fix this?

![image](https://user-images.githubusercontent.com/29949806/178115658-949af689-357e-445c-abf5-971bea94ff75.png)

**Comment by kingmaster772** [comment]
This is happen on my VPS with:
- 3 Core CPU
- 40 GB Disk Space (35GB Free)
- 3 GB Ram
- ubuntu-20.04-x86_64-minimal Operating System

**Comment by Alnaggar94** [comment]
What cloud provider are you using? Are you sure you run the installation command with root privilege?

I see the server is Apache?? Cipi comes with nginx only are you sure you installing it on clean OS?

**Comment by kingmaster772** [comment]
yes, i installed on clean OS with root privilege but my server using Apache. thanks for feedback, i'll try again and keep this issue up to date

**Comment by Alnaggar94** [comment]
I think it's a conflict because you have Apache with nginx in the same time. Apache shouldn't be there if you installed it on clean OS.

**Comment by kingmaster772** [comment]
It solved simply by stopping _apache2_ service and start _nginx_ service. In case anyone having issue unable to login is maybe blocked by your firewall/antivirus, and this is maybe happen only for http connection

![image](https://user-images.githubusercontent.com/29949806/178152196-16c9a55c-cbe0-4003-b515-1faedcd08a7b.png)
