### ISSUE TITLE
Would Cipi be a good fit for my needs....

### ISSUE THREAD

**Issue by bonelifer** [andreapollastri/cipi#434]
I don't need multiple servers. I'd like to have a way to host my personal home services and be able to get to them from outside my network. Much of what I have will be docker installed. So I need a way to proxy those, to different sub-domains, and have let's encrypt builtin. Also leverage an SSO across the board even for non-authenticated services.

**Comment by LemarinelNet** [comment]
At the moment cipi doesn't provide "proxy services" to redirect your domains/subdomains to your docker containers.
