### ISSUE TITLE
how to change php.ini settings for a domain in cipi control panel

### ISSUE THREAD

**Issue by workbykiran** [andreapollastri/cipi#435]
I saw all the configuration files are owned by root and thus not able to modify any changes in php.ini or specific settings for specific domain at php-fpm level. Can you help me how i can change settings?
Ex: I would like to change max_execution_time to 300 and max_input_vars to 2004 for a specific domain. 
Iam OK even if changes applies to all the domains in cipi control panel hosted.
Kindly suggest.

**Comment by axxiomdigital** [comment]
The only way I found to change the php.ini settings is to download the source files and amend the install details but that did not work 100%. Cipi is perfect because it's simple but just missing the ability to amend the php.ini settings

**Comment by workbykiran** [comment]
but i already have an existing cipi server with mutiple websites (applications) hosted. How can i change existing php configuration. I even tried to change nginx configuration as stated in the documentation as below:

Customize site nginx conf
You can customize every Site nginx configuration using cipi root user:
    Run ssh cipi@<server-ip>
    Run sudo nano /etc/nginx/cipi/<app-user>.conf
    Edit your custom configuration
    Run sudo systemctl restart nginx.service

but iam not able to edit any such file as it is owned by "root" userr and "cipi" user is unable to do any such changes and thus got stuck there. Same issue with php settings as well.
Can you please guide for any solution.

**Comment by arwinvdv** [comment]
@workbykiran try `sudo su` when logged in as cipi

**Comment by workbykiran** [comment]
perfect. Was now able to update php settings and nginx settings as well. Thank you very much.

**Comment by juliomgm** [comment]
i am testing cipi and i cant change detected max filesize in wordpress.

Found the location of PHPINI in go.sh and i changed 

--- /etc/php/7.4/fpm/conf.d/cipi.ini

memory_limit = 256M
upload_max_filesize = 2560M
post_max_size = 2560M
max_execution_time = 3600
max_input_time = 3600

--- /etc/php/7.4/fpm/php.ini

max_execution_time = 180
upload_max_filesize = 2560M
post_max_size = 2560M

--- /etc/nginx/nginx.conf
http {
    # ...
    client_max_body_size 2560M;
    # ...
}

and i still cant upload a 800mb file in a wordpress site.
Can anyone help? 
Thanks.
