### ISSUE TITLE
Is Cipi 4 still coming?

### ISSUE THREAD

**Issue by banago** [andreapollastri/cipi#459]
Hi @andreapollastri,

I just discovered Cipi and I'm loving it this far. Is Cipi 4 still coming?

Thanks,
Baki

**Comment by gagegogan** [comment]
I'm doubtful that it'll come. No commits in ages.

**Comment by fastmover** [comment]
Let me know what I can do to help. I love control panel.

**Comment by arwinvdv** [comment]
I see that @andreapollastri has made changes to private repositories the last months. Hopefully it is cipi4 :)

**Comment by rekliner** [comment]
It seems he might be retiring this repo for that one, but both have plenty of activity.  It appears he's using that one to test with Laravel 10 as opposed to this one on Laravel 9. He's clearly working hard to finish it up.

**Comment by jpmurray** [comment]
> @andreapollastri Can we have an ETA?
> 
> Can someone here update CIPI 3 with PHP 8.2 and all the dependencies. This shouldn't be complicated... We should at least get security updates.

if it's not complicated, you can always make a PR yourself !

**Comment by gagegogan** [comment]
Why is this closed? We still don't have an answer

**Comment by yolanmees** [comment]
Cipi hasn't had an update for over a year. So I'm trying to bring life to Cipi again. I forked Cipi to a new repository. I am working on a migration and easier update system first.

https://github.com/yolanmees/Spikster
