### ISSUE TITLE
deployment on scaleway error

### ISSUE THREAD

**Issue by xavierle** [andreapollastri/cipi#5]
ubuntu 18.04

<\ SETUP COMPLETE >

URL: http://
USER: admin@admin.com
PASS: 12345678

Enjoy Cipi :)

nothing on the access IP of the server

scaleway is a bit special

the access ip to access the server is not the same it shows by ifconfig
so maybe some additionnal config shall be done

**Comment by xavierle** [comment]
installation of the panel on a more standard server is finalizing OK.
i tell you about a node  installation on scaleway :

here is some result from installation of node on scaleway

MySql service: OK!




bash: line 99: sudo: command not found


bash: line 101: sudo: command not found


bash: line 103: sudo: command not found


bash: line 105: sudo: command not found


bash: line 107: sudo: command not found


bash: line 109: php: command not found
Please Check the Install Services, There is some Problem


PHP-FPM configuration: OK!


bash: line 123: sudo: command not found
root@scw-kind-sinoussi:~# wget -O - http://51.15.10.66/scripts/install/624116740276ceef159fe97463682b09/ | bash
--2019-06-24 20:04:23--  http://51.15.10.66/scripts/install/624116740276ceef159fe97463682b09/
Connecting to 51.15.10.66:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://51.15.10.66/scripts/install/624116740276ceef159fe97463682b09 [following]
--2019-06-24 20:04:23--  http://51.15.10.66/scripts/install/624116740276ceef159fe97463682b09
Reusing existing connection to 51.15.10.66:80.
HTTP request sent, awaiting response... 403 Forbidden
2019-06-24 20:04:23 ERROR 403: Forbidden.

**Comment by andreapollastri** [comment]
Hi Xavierle,
as you told, scaleway is a bit special!
So I think that you have to download go.sh script and custom it declaring your VPS IP at row number 9:

IP=$(dig +short myip.opendns.com @resolver1.opendns.com) 

become 

IP=123.456.789.0 (your IP)

than upload the custom go.sh on your server and run it as root.

Let me know if it works!

**Comment by andreapollastri** [comment]
Did you solve it?

**Comment by xavierle** [comment]
I will test is later on

**Comment by andreapollastri** [comment]
OK! Let me know!
And thankyou also for your e-mail... I will reply soon... in the meanwhile I notice to you that I just compile a roadmap of this project. You can find it here:  https://github.com/andreapollastri/cipi/projects/2
If you need or if you want suggest any other feature you can open an issue so I put it into a sprint if it's a valid new feature.
Thankyou for your feedback :)

**Comment by xavierle** [comment]
this readmap is already something niceto achieve !
