### ISSUE TITLE
Move to PHP 7.4

### ISSUE THREAD

**Issue by andreapollastri** [andreapollastri/cipi#59]

**Comment by rockethost-israel** [comment]
@andreapollastri Hi, any progress wilth this update and the project? you mentioned that soon will be with some great updates in verstion 2.0 but as i see its stuck for a few months...

**Comment by andreapollastri** [comment]
Hello @rockethost-israel , hello everyone... in the last months I'm working very hard on my current main job and outside of my job I had some issue but I will take care about Cipi very soon, I think that this summer I will release a second version within these new features:
- Laravel 7 based
- PHP 7.4 / MySql 8 support
- ngnix integration
- backups / dumps
- other minor fix
I hope that you will enjoy it!

**Comment by andreapollastri** [comment]
Done :) ...deployed in v2
