### ISSUE TITLE
Request for Features

### ISSUE THREAD

**Issue by Manishfoodtechs** [andreapollastri/cipi#74]
Cipi is lightweight and very good to work with. However, I would like to see the following features in future releases:
1. The option of Nginx / lightspeed (open)
2. LXC / Docker containers.
3. Terminal (browser based)
4. backup to google drive / dropbox.
5.SSHFS with local system may be a unique feature

**Comment by andreapollastri** [comment]
Hi @Manishfoodtechs ... thank you for the issue.
I currently am developing a new version of Cipi based on nginx.

So the response to your questions are:
1 - next version (that will be release on 1th May) will be nginx based
2 - tell me more about this request... I think that if you use Docker you can't use Cipi or if you use Cipi you don't have to use Docker but let me know what is your idea!
3 - good idea! I'll work on it!
4 - I'm working on an optional daily s3 backup
5 - what's your idea about SSHFS?

Let me know
Thank You

**Comment by Manishfoodtechs** [comment]
So the response to your questions are:
**1 - next version (that will be release on 1th May) will be nginx based**
_**This is great news. Awaiting...**_

**2 - tell me more about this request... I think that if you use Docker you can't use Cipi or if you use Cipi you don't have to use Docker but let me know what is your idea!**

**_with a button click, you can create 'containers'. Ubuntu provides LXD containers. These are very powerful. Shell commands are very simple._** 

`<?php
$output = shell_exec('lxc exec ubuntu:20.04 cipi');
echo "<pre>$output</pre>";
?>`
This will create ubuntu 20.04 server in a container. Then again, cipi can be installed in this container.

**3 - good idea! I'll work on it!**
This is really a key feature. However, till then you can allow one-click cockpit.(https://cockpit-project.org/)
 
**4 - I'm working on an optional daily s3 backup**
great. As for now I am using this https://www.techrepublic.com/article/how-to-sync-your-linux-gui-less-server-to-your-cloud-service-with-rclone/

**5 - what's your idea about SSHFS?**
SSHFS advantage:
1. Mount remote hard drive to your Server.
2. Push file from local PC to server directly.
here is something I guided by and implemented https://www.digitalocean.com/community/tutorials/how-to-use-sshfs-to-mount-remote-file-systems-over-ssh

Let me know
Thank You

**Comment by andreapollastri** [comment]
Ho @Manishfoodtechs ... I just released Cipi v.2 (in beta version).
Now is ngnix based. :)
About Docker... you can dockerize easily Cipi or any other LEMP application within https://github.com/andreapollastri/easydock (write me if you need help).
About SSHS, Terminal and Backup I'll work on them and they will be released in the future.
I close the issue. Thank You. :)
