### ISSUE TITLE
s3 Automated Backups

### ISSUE THREAD

**Issue by andreapollastri** [andreapollastri/cipi#76]
s3 filesystem and db dump automated applications backup

**Comment by rockethost-israel** [comment]
i am using Backblaze B2 Cloud Storage years and its much cheaper to compares to Amazon S3.
maybe you can use this library as a start point:
https://github.com/hpolthof/laravel-backblaze

**Comment by rockethost-israel** [comment]
also i think it will be a good idea to restore db from backup in one click.

**Comment by rockethost-israel** [comment]
@andreapollastri maybe to use same library for multi location like this?
https://github.com/backup-manager/backup-manager
