### ISSUE TITLE
Digital Ocean integration

### ISSUE THREAD

**Issue by andreapollastri** [andreapollastri/cipi#79]
Integrate DO api into Cipi for automated VPS deploy via Cipi (maybe also with other providers).

**Comment by rockethost-israel** [comment]
HI @andreapollastri 
you can use this librarie for this task:
https://github.com/GrahamCampbell/Laravel-DigitalOcean

**Comment by andreapollastri** [comment]
Yeah... Thank You @rockethost-israel ... I'll evalute it! Thank You

**Comment by andreapollastri** [comment]
I close the issue and I will re-open it when v3 will be in develop
