### ISSUE TITLE
apache + nginx support

### ISSUE THREAD

**Issue by andreapollastri** [andreapollastri/cipi#8]

**Comment by Ostap34JS** [comment]
How about only nginx support?

why you prefer apache?

Thanks...

**Comment by andreapollastri** [comment]
Hi osbre,
you are right!
nginx is powerful than apache but I think that apache for basic users that need to use .htaccess file and don't have advanced skills is better than nginx... anyway I will release a feature that lets you to decide if run any single application in:
- apache only
- apache + nginx
- nginx only

You have to wait about 1/2 months.

Best
Andrea

**Comment by ershagen** [comment]
Any news? 💃

**Comment by LewisSmallwood** [comment]
Andrea, do you need any assistance?

I know apache + nginx can be configured in a way in which allows Nginx to proxy traffic to Apache. 

For example, running apache to listen on port 81 with `<VirtualHost 127.0.0.1:81>` and then, in the nginx server block configs: 
```
location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-SSL on;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://127.0.0.1:81;
}
```

Would you like to discuss via email?

**Comment by andreapollastri** [comment]
Yeah, thank you so much Lewis Smallwood.
Currently I'm working on a new version of Cipi with ngnix traffic proxy that will be released on about 15th october. 
Sorry if I'm not so responsive with new features but I'm very busy with my current business job.
I promise that Cipi Version 2 will be very better than version 1. :)

Talk to you soon.
Thank You for all advices and support.

Andrea

**Comment by brandy** [comment]
@andreapollastri Any updates on this? I'm looking to switch to cipi but need nginx support.

Thanks!

**Comment by neo3k** [comment]
Hello! Congratulations on your good work. I am looking forward to this new feature.

**Comment by andreapollastri** [comment]
Done ... deployed in v2! ;)

**Comment by andreapollastri** [comment]
Hi devs! Cipi is now in version 2 (beta) with nginx support! :)

Let me know your feedback!
