### ISSUE TITLE
Older version of Nginx and MySql Server 

### ISSUE THREAD

**Issue by aonsyed** [andreapollastri/cipi#85]
Ubuntu 18 branch isn't up to date, for example latest version of Nginx is 1.18, the version being installed with CIPI (1.14) hasn't even been maintained for more than a year now. 
Solution of the issue is to add Nginx repo and install latest version from there
Secondly, Nginx comes with fastcgi cache it would be amazing if that's installed too. 
Thirdly MySQL version is 5.7, although being maintained, latest version with security bugs hasn't been updated to Ubuntu repo, the latest version is 8.0 and that was released two years ago too.

**Comment by andreapollastri** [comment]
Hi @aonsyed ... Thank You for this issue!
You are right! Currently I'm working to move the project to last version of nginx but maybe I'll leave MySql 5.7 in this version because many current projects in the world support it and not 8!
I'm working to a Cipi Ubuntu 20 version with MySql 8... I'll notice to you when it will be ready!

**Comment by aonsyed** [comment]
Thank you, yes that is understandable.

**Comment by andreapollastri** [comment]
@aonsyed  I decided to create a Cipi v3 that maybe will be released in the next months with MySql 8 support, updated nginx and based on Ubuntu 20 LTS. I'll re-open this issue when v.3 is ready! 
Thank You for the feedback

**Comment by andreapollastri** [comment]
Hi @aonsyed  Great news for you!
Version 2 is now in stable version and it supports Ubuntu 18.04 both with 20.04 so...
if you install Cipi on a 18.04 server you will get:
- nginx 1.14
- mysql 5.7
- node 12
but if you install it on a 20.04 server you will get:
- nginx 1.17
- mysql 8
- node 14
PHP-FPM 7.2, 7.3, 7.4 and other stuffs are common for both.

Bye :)

**Comment by aonsyed** [comment]
Thank you for the update
