### ISSUE TITLE
Server Status Monitor with notifications

### ISSUE THREAD

**Issue by andreapollastri** [andreapollastri/cipi#88]
Every minutes server monitor with graph log in dashboard and notifications for:
- high resources alert
- low hdd free space
- no server ping
In settings user can set mail, slack and telegram notifications.

**Comment by rockethost-israel** [comment]
also, clipi must have "Service status" that allow to see and control each service status like:
php, mysql, nginx and etc...
admin can start, stop and restart any service.

**Comment by andreapollastri** [comment]
I close the issue and I will re-open it when v3 will be in develop
