### ISSUE TITLE
Teams and Roles Support

### ISSUE THREAD

**Issue by rockethost-israel** [andreapollastri/cipi#92]
its good ideal to manage permissions per user & per server.
so as team admin we can allow other team members (devs and users) to have control over server functional.

**Comment by andreapollastri** [comment]
Good idea... thankyou @rockethost-israel 

I'll working on it for v.3

**Comment by andreapollastri** [comment]
I close the issue and I will re-open it when v3 will be in develop

**Comment by Alnaggar94** [comment]
@andreapollastri 

I hope we can see this feature in Cipi V4.
