### ISSUE TITLE
Staging feature 

### ISSUE THREAD

**Issue by rockethost-israel** [andreapollastri/cipi#93]
one of the must have feature is to allow user/dev to create in one click "Staging" for his project (site).
basically we need to to create new subdomain clone all the files and db.
then, when user/dev finish working on the "Staging", in one click he can move "Staging" to "Production".

**Comment by andreapollastri** [comment]
You can use "alias" or Git to do it! I think that it something "old" working in that way... today every dev MUST use Git!
