### ISSUE TITLE
MariaDB Support

### ISSUE THREAD

**Issue by rockethost-israel** [andreapollastri/cipi#96]
HI @andreapollastri its a good idea to add MariaDB and allow to switch between mysql and MariaDB. by far MariaDB give better performance than mysql.

**Comment by andreapollastri** [comment]
Yeah... this is an important features. I will released it soon! Thank You!

**Comment by andreapollastri** [comment]
Hello I decided to move it in v.3... I close issue and re-open it for v.3. Thank You
