### ISSUE TITLE
Tools to improve security

### ISSUE THREAD

**Issue by rockethost-israel** [andreapollastri/cipi#97]
we can use tools like:

Antivirus
https://www.clamav.net/

for malware:
https://www.rfxn.com/projects/linux-malware-detect/

or both:
https://revisium.com/aibo/

ModSecurity - firewall
https://modsecurity.org/

Nginx Block Bad Bots
https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker

**Comment by andreapollastri** [comment]
Thankyou, I will test them and maybe I will put some of them in next version. Thank You for the advice!
