### ISSUE TITLE
App Optimisation

### ISSUE THREAD

**Issue by rockethost-israel** [andreapollastri/cipi#99]
add support for cache layers to improve the app speed.

Varnish HTTP Cache
https://varnish-cache.org/

memcached
https://memcached.org/

Redis
https://redis.io/

FastCGI cache module in NGINX

**Comment by andreapollastri** [comment]
OK @rockethost-israel ... Now I'm using OP cache but I will add application caching system as Redis and Memcached.

I close this issue and re-open it in v.3 .

Thankyou
